### ISSUE TITLE
Parsing doesn't seem to be working with Strings

### ISSUE THREAD

**Issue by zmolahah** [bensku/Skript#1015]
I used this code
```
left click:
  player is an op
  cancel event
  send "&a%location of clicked block%"
  set {_loc} to "%location of clicked block%"
  replace all ".5" with "" in {_loc}
  set {_loc} to "%{_loc}%" parsed as location
  send "&c%{_loc}%"
```
Normally this should return as [this](https://puu.sh/yFdZp/dd672c0ccc.png) I remember doing this many times in the past. Instead I am getting [this](https://puu.sh/yFe7q/b19777a5c4.png)

I get this same problem when I try to parse as a date using this code

```
command /test:
  trigger:
    set {_now} to "%now%"
    set {_now} to "%{_now}%" parsed as date
    send "&c%now%"
```

**Comment by Snow-Pyon** [comment]
Well, you might not be remembering right because locations never been parseable. I always used this function for it:
```
function text2Loc(loc: text, world: world) :: location:
   set {_locpart::*} to {_loc} parsed as "x: %num%, y: %num%, z: %num%"
   return location({_locpart::1}, {_locpart::2}, {_locpart::3}, {_world})
```

**Comment by Pikachu920** [comment]
Dates have also never been parseable

**Comment by TheBentoBox** [comment]
Closing this since, as has already been pointed out, both of the things you're saying you used to be able to do were never possible, at least not with vanilla Skript. Maybe an add-on added support for it at some point but this isn't a bug since it never was possible. You can (I suppose) feel free to open another issue report requesting this feature, which I could mark as an enhancement, but it's pretty easy to write a function yourself to parse these types. Ask on the forums if you need help!

**Comment by zmolahah** [comment]
Most likely was an addon or something simular than I suppose. I haven't used vanilla Skript since Njol went AWOL and I have been using many addons in the past. @Snow-Pyon thanks for the function I already set up some for this I just want to try and report any possible bugs I run into
