### ISSUE TITLE
Skript Command Show Error in Mojang Help Command

### ISSUE THREAD

**Issue by CormanYT** [bensku/Skript#1058]
So, I'm using /help, the one from default no Essentials or anything and I get this...
[https://goo.gl/2ZyDz5](url)
It says stuff like /skript:<command> instead of just the /<command>.
Support required.

**Comment by TheBentoBox** [comment]
Skript doesn't do anything itself to display a command response to `/help` like this, and showing `/skript:` before the command name is completely normal because commands (when registered properly) are namespaced by plugin, meaning every command has a variant that should show up as `/plugin:command`.

**Comment by CormanYT** [comment]
Yes I know that. But, for the /help, the /<command> should override the /<plugin>:<command> as the /<command> will show as the default I know /<plugin>:<command> works, and it's not a glitch but I think it's more user friendly and not good if it shows like that. Let me give an example.

Skripts official command /skript shows /skript in /help, instead of /skript:skript in /help. That being said, the other skript commands shouldn't be like that.

**Comment by Syst3ms** [comment]
that's a bukkit thing, there's nothing we can do about it
