### ISSUE TITLE
Recommendation: And

### ISSUE THREAD

**Issue by CormanYT** [bensku/Skript#1071]
So, I have a recommendation for Skript. This Skript would help make some scripts more lightweight, and be a help in the while-run for some skripters. Ands. Now skript has support for these types of ands:

> If message contains BLOB and PIZZA:
        message "&e&lYou have unlocked the code!"

However it doesn't have these:

> If player has permission "example.whatever" and {admins::*} contains player:
        message "&5&lAdministration Mode On!"

Since it doesn't have those we have to do stuff like this:

> If player has permission "example.whatever":
        if {admins::*} contains player:
            message "&5&lAdministrastion Mode On"

I think adding those would be a lot easier!

**Comment by Snow-Pyon** [comment]
1. This isn't possible without doing some big rewrite on how conditions work. It's just not feasible right now.
2. Let me correct you, if we were gonna implement this somehow, it wouldn't make your script lightweight nor faster in any ways, it'd be just less to write and to be honest, it isn't worth the effort right now.
3. Some addons have implemented similar features already, like skQuery's check expression but it's kinda slow as it was badly made.
4. I'm closing this because I'm pretty sure someone has suggested it before and even if not, this is a planned feature which is gonna be implemented at some point,  but not now with the current state of Skript.
