### ISSUE TITLE
On Entity Dismount does not work

### ISSUE THREAD

**Issue by GermanMinerDE** [bensku/Skript#1147]
If I use the "On Entity Dismount" event, it says: "can't understand this event."

The event is directly from Skript, integrated in the Skript documentation here http://bensku.github.io/Skript/events.html#entity_dismount

**Comment by GermanMinerDE** [comment]
- Sorry: Works with "on dismount:"

**Comment by TheBentoBox** [comment]
Just specific info for posterity's sake, the syntax that shows in the event documentation is what goes directly after `on`, so since the syntax doesn't use the word `entity`, you can't either. I do see how it can be misleading since the header for that syntax says `On Entity Dismount` even though that's not a proper syntax for the event. You should just always reference the `pattern` section below the header as opposed to the section header itself.
