### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by JordyEGNL** [bensku/Skript#1180]
Im getting this error:
https://hastebin.com/uvanuxoleh.md

When i try to use this file:
https://hastebin.com/orusirilix.vbs

**Comment by bensku** [comment]
Your Skript jar might be corrupted. Try downloading the latest version again and see if it works. If not, it is likely a Skript bug.

**Comment by JordyEGNL** [comment]
I tried the latest and beta 32.

**Comment by TheBentoBox** [comment]
The syntax that is sending errors in your first example is not a vanilla Skript syntax; Skript now has a fair amount of inventory support built-in, so you should try using our vanilla syntaxes. Update to dev34 and change your `open chest` syntaxes from this

`open chest with 3 rows named "&2Computer &f- %player%" to player`

to this:

`open chest inventory with 3 rows named "&2Computer &f- %player%" to player`

Note the word "inventory" being added as that is what the vanilla Skript syntax is for custom chest inventories. [See here](http://bensku.github.io/Skript/expressions.html#ExprNewInventory). Otherwise, I agree with Bensku that your Skript JAR looks corrupted in that last error report, so make sure you're using a **new, freshly downloaded JAR** for dev34 from the [releases](https://github.com/bensku/Skript/releases) page.

Let me know if any of this helps with your issues.
