### ISSUE TITLE
Umbaska + Skript 1.10 won't work together ...

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#120]
Can you please check it out:
https://forums.skunity.com/t/addon-umbaska-2-0-big-announcement/137/1435?u=pepper82

And this:
https://forums.skunity.com/t/addon-umbaska-2-0-big-announcement/137/1456?u=pepper82

I have attached my versions of Skript and Umbaska if that helps.

[plugins.zip](https://github.com/bensku/Skript/files/354882/plugins.zip)

It's the only reason I am unable to update my server to 1.10. Let me know if you need more details.

**Comment by JKGamerxD** [comment]
This isn't a problem of Skript, maybe it's because two have the ClickType.class registered. But nfell said "Umbaska works with the Bensku version, but doesn't support it." so...

**Comment by bensku** [comment]
I'm not really interested in fixing Umbaska stuff on Skript's side - again. Won't fix, unless someone else does it (PR will be accepted, if I get one).

**Comment by bloggy** [comment]
I think Skript should be able to support addons like umbaska because they offer great enhancements to the basic Skript plugin which many people already use on their servers (me too). I can not simply deactivate Umbaska because it's an essential part of my server. So I'd really appreciate it if you could find a solution as soon as possible. Thanks for your help!

**Comment by Pilvinen** [comment]
The thing is - you should be complaining about this to the person responsible for Umbaska.

**Comment by Sashie** [comment]
I honestly think the person who decided to put some new syntax into their plugin without even checking if it existed first(regardless of what they feel like using) It is them that should have worked together with the community and talked with the devs of Umbaska about adding some of their stuff into Skript as core functionality(which in my opinion is a good thing for some stuff) but instead there is now a burnt bridge over this issue.

**Comment by bensku** [comment]
Well, as I said, I might be able to fix this... But if I do so, even then some Umbaska features might be broken. Same for other addons.

@Sashie The reason I picked up Skript's development was that I and @Pilvinen needed some features and especially bugfixes. While my version might be helpful for other server admins, that is not the original purpose I had. If it works, good. If it doesn't, I'll try to make it work - if I have time.

I have probably said it already, but still... I don't really like closed source addons (or other plugins, unless for one specific server). Considering that, I don't see very good reasons to provide any support for them - other than the fact that you want me to do so.

If someone would like to help me with Skript, all pull requests are welcome - and most have been accepted. Especially on issues tagged "help wanted", I'm really not interested (and/or skilled enough) to solve the problem.

Since you (all) asked, I will _try_ to hack around _this_ issue. No promises and no ETA; I'll tell you when/if it is ready. Could be few days, but could be way longer time...

**Comment by Pilvinen** [comment]
Have I missed something? As far as I know there has been absolutely no argument over anything. We simply forked Skript because nfell's version at the time had failed to address some critical bugs which made that version of the Skript useless for our server + the development pace was too slow for us.

You are of course free to use nfell's version if it works better with Umbaska (I haven't kept track what's going on there, I have 100% no idea) or you can make a pull request if you have the necessary skills to lend a hand or even make your own fork of this repo.

Personally I don't use Umbaska because I've had too many issues with it in the past. And like bensku said it's closed source - so it's rather difficult to fix any bugs they might be having with our version of Skript.

But as far as I know there are absolutely no burnt bridges or even a single argument between us.

If you wish to continue this discussion please do so at the forums. This is only meant for bugs.

**Comment by nfell2009** [comment]
@Pilvinen Actually, @bensku is responsible. Umbaska worked fine before he added inventory types or whatever (I haven't paid attention to this fork either. No hard feelings). I also have no problem with your fork existing. Your reasoning is completely valid, you needed Skript now, not when I had time, which is understandable.

**Comment by bloggy** [comment]
Guys, there must be an option to get bensku's skript work with umbaska. Why can't both authors come together and discuss this? Why not give bensku the option to look into the source of umbaska to make it compatible? Sorry, I am not a developer but just a server owner who is not able to update to 1.10 because Skript + Umbaska do not work together and I am not the only one.

**Comment by Nicofisi** [comment]
Is there any easy method to check whether someone is using the original Skript / fork by other author or yours, with Java?

**Comment by nfell2009** [comment]
@bloggy this Skript fork is unofficial, not support by Umbaska and not used to build Umbaska. It is Bensku who broke it, not us. He is the one that needs to speak to me. I'm not sorting this shit out.

@Nicofisi, there is no differences in plugin.yml or the main class.

**Comment by bensku** [comment]
I expect you to stop arguing here, or this will be closed again. If know of something else that is broken, then please reply. Also, if you would like to help me with this, reply; otherwise I'm going to try something myself.

**Comment by bloggy** [comment]
Thanks for trying to help and fix this, really appreciate it.
I just tested your latest 1.10 version of Skript with the latest SkStuff Addon (can be found [here](https://forums.skunity.com/t/1-10-ready-skstuff-v1-6-3-6-nbt-worldedit-pathfinders-more/)) and it's incompatible as well. Here is the console error. Let me know if you need any more information (logs, plugin versions, etc.). I am willing to help with whatever I can do.

http://hastebin.com/buwaroguhe.avrasm

**Comment by bensku** [comment]
@bloggy That error message is more likely related to too new WorldGuard version. Please try downgrading it for now.

**Comment by TheBentoBox** [comment]
@nfell2009 You know I love you but I think this is a crappy attitude to have. There is no official fork anymore, and if there had to be one, it would be this one, not yours. You haven't updated yours in ages and there are just as many people or more using this one, as far as I can tell. Going around saying you don't care about adding compatibility to a version of Skript a huge portion of the community is using only causes an unnecessary rift. We don't need to start dividing the Skript community by what fork they use, when it can be solved by addon developers simply checking if their syntax has been registered already.

I get that you guys don't get paid and don't have to be doing this for us, but by taking that step to create an addon or a fork of Skript, developers are creating something that people begin to rely on. Nobody can force you to try to make things compatible, and you're all free to run around and point fingers and continue to say "he did it not me!!!!", but it's really helping nobody.

There are now multiple Skript forks as well as tons of addons, sometimes you guys will have to go that extra step to make things work together. We're a big jumbled community and this is a wonderful fork that many people are using, and purposefully pointing fingers at each other gets nothing done. In the time you guys have taken complaining to each other, this could have been resolved multiple times over.

That's just my 2 cents. I hope your fix works @bensku, and I really hope to not see more arguing of this type in the future, because I personally just find it awkward and counterproductive. Hopefully you guys don't hate me now :^*

**Comment by nfell2009** [comment]
@TheBentoBox, Bensku caused the problem yet I'm being held responsible which is total bs. I'd hardly call my attitude crappy, I'm defending my software. My point before is that Umbaska does not rely on Benskus version, his version is neither approved by Njol nor The Umbaska Project and he added his "feature", after Umbaska, so caused it himself. It isn't as simple as checking if syntax is already registered. There is no way to. 

Bensku has made no differences between knowing if its normal Skript or his fork. So its not that simple.

**Comment by TheBentoBox** [comment]
Well then I agree Bensku should make those differences so addon devs are even physically able to support the different versions should they choose to.

I also don't mean to imply it's all the fault of you or addon devs in general and not Bensku. I'm just giving my perspective as an outsider (a programmer, but one that doesn't develop Skript or its addons, I'm just a user). It has seemed like there's been a lot of arguing with little progress, but of course I can't know as much as you guys do about it while not being one of the devs.

**Comment by Pilvinen** [comment]
We can talk about this if you like but, Please, continue this discussion here in this thread:

https://forums.skunity.com/t/benskus-fork-skript-for-minecraft-1-9/4588

This is a bug tracker and not a place for a debate. Also this bug has only been open for two days, so relax. 

We are also in the progress of developing our own game AND updating Skript for the Minecraft community at the same time. 

Please, express your opinions here:

https://forums.skunity.com/t/benskus-fork-skript-for-minecraft-1-9/4588

**Comment by nfell2009** [comment]
@Pilvinen, yeah, that's fine. Sorry to de-rail your issues section

**Comment by Nicofisi** [comment]
@bensku @Pilvinen as a workaround for now, can we ask for any simple way to check whether the server is using your fork or another one?
For example, could you add a simple method which does nothing,
```java
public void bensku() {

}
```

```java
		// Addon
		boolean bensku = false;
		try {
			Skript.bensku();
			bensku = true;
		} catch (NoSuchMethodError ex) {
			
		}
```
or you can just annotate the main class of Skript:
```java
@SuppressWarnings("lol")
public final class Skript extends JavaPlugin implements Listener {
```
so we can
```java
boolean bensku = Skript.class.getAnnotation(SuppressWarnings.class) != null;
```
that would help a lot

**Comment by nfell2009** [comment]
@nicofisi all they need to do is add Bensku as an author in plugin.yml and we can check that.

**Comment by Nicofisi** [comment]
@nfell2009 that's also a solution xD

**Comment by bensku** [comment]
Will add plugin.yml as author, and maybe something else.
