### ISSUE TITLE
On Block Damage:

### ISSUE THREAD

**Issue by Fix3dll** [bensku/Skript#1214]
Tested with 1.8.8 and 1.12.2. Used lastest skript. Block damage working like on mine/break.
block damage:
	message "Test"
	cancel event
Block damage isnt cancel event shen player starting to mine block? Its only prevent mine block. Not block damage.

**Comment by TheBentoBox** [comment]
Unfortunately, that's just how block damage works; the event is getting fired when you first click on the block, but the animation is client-side so canceling the event on the server doesn't stop it and there's no way to do so. That's why [the documentation for `on block damage`](http://bensku.github.io/Skript/events#block_damage) says "you can usually just use the leftclick event for this"; the event isn't all that useful. Not Skript's fault.

**Comment by Fix3dll** [comment]
@TheBentoBox I remember 1 event which player when use the left click on any block it cancel event (Like disable targeting block client side) Can you help me for this event?
