### ISSUE TITLE
Vehicle exit event not triggering

### ISSUE THREAD

**Issue by Arcrimonia** [bensku/Skript#133]
`on vehicle exit:`
Cannot be understood by Skript. Has this been removed?

**Comment by JKGamerxD** [comment]
I can confirm this. Also I checked the SimpleEvents.class and it's not registered. @bensku only need add this to the SimpleEvents.class:
```Java
		Skript.registerEvent("Vehicle Exit", SimpleEvent.class, VehicleExitEvent.class, "vehicle exit", "exit[ing] [a] vehicle")
				.description("Called when an entity exits a vehicle.")
				.examples("")
				.since("1.0");
```

**Comment by bensku** [comment]
This is not a bug, instead it is caused by certain interesting decisions in Spigot API. Only entities player can normally (in vanilla) ride are counted as vehicles. This includes pigs, horses, boats and minecarts currently.

For other entities, mount/dismount should work. On Skript's side, code is quite similar, it just takes different Spigot events in.

**Comment by bensku** [comment]
Wait a sec. This event doesn't exist. That's wrong, it should work for legacy scripts.

**Comment by JKGamerxD** [comment]
That is what I mean on my above comment :sweat_smile:
