### ISSUE TITLE
bug.

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#222]
```
on block damage:
     cancel event
```
It does not apply to paintings and item frames.

**Comment by Namnodorel** [comment]
That is, because paintings ans item frames are, in fact, not blocks but entities. If the event would be triggered, it would also be triggered if you hit a sheep. This is not a bug, it is how Minecraft has implemented them. You'll have to add another event listener for entities, check if the entity type is itemframe or painting and then cancel it in order for this to work.

**Comment by FUZIK** [comment]
I thought that this is a bug in the Sk xD
alternative:
```
on break:
    cancel event
```

**Comment by bensku** [comment]
Block break event applies for item frames, since it is manually codedbin Skript. However, block damage does not and will not - it should only be used to prevent block break animation which isn't problem with item frames anyway.
