### ISSUE TITLE
What do you think about .YML?

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#230]
What do you think about adding support .YML?

**Comment by bensku** [comment]
For what purpose? Configuration of scripts, which everyone is supposed to be able to edit?

**Comment by F8te** [comment]
For a Java plugin that's understandable because edit a Java plugin would be more hard to do, but for a script that you can edit just with a text editor, it wouldn't be an issue. Also, there are addons that already has the YML feature and another file features as SkUtilities. Add it to vanilla Skript would be useless.

**Comment by TrademarkTM** [comment]
YML is already supported by skQuery:
https://forums.skunity.com/t/skquery-reading-and-writing-yaml/620
