### ISSUE TITLE
Can't place blocks from off-hand

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#25]
Dev9b:

Can't place blocks from off-hand when main hand is empty.

**Comment by bensku** [comment]
For me it seems to work perfectly, but I'll do some debugging to find possible causes...

**Comment by TheBentoBox** [comment]
I'm also getting this. As Pilv said, it only happens when you have a block in the offhand and the mainhand is completely empty. e.g. Having a pick in the mainhand and torches in the offhand works fine, you can place them. But then if you deselect the pick and have an empty hand, it seems to cancel the placement events.

**Comment by bensku** [comment]
Hmm... Is this fixed? I can not reproduce the problem, and could not do so with current release build either. We'll see when I upload next release :)

**Comment by TheBentoBox** [comment]
It was working for me last night with the latest release. It was likely fixed along with you fixing all of the right click inconsistensies.

**Comment by bensku** [comment]
Well, that's good. Closing.
