### ISSUE TITLE
Not checking for .sk at end of file.

### ISSUE THREAD

**Issue by Jduffygames** [bensku/Skript#257]
I have a skript that is named "disabled" with no .sk at the end and it is still working.

**Comment by bensku** [comment]
Was this not the case before?

**Comment by Jduffygames** [comment]
No. If it is named "disabled" it should not be enabled.

Unless you name it "disabled.sk"

**Comment by F8te** [comment]
well, it's not a big issue really, just put a "-" at the start of the file's name and it would be disabled then.

**Comment by Jduffygames** [comment]
@F8te 

Take a look at this bug report... https://github.com/bensku/Skript/issues/253 :)

**Comment by bensku** [comment]
For me this is working. So the question is, do you have addons installed?

Anyway, I recommend trying with next build. I might have fixed this without noticing it.

**Comment by RoyCurtis** [comment]
I've run into this issue also; it appears that Skript is now trying to parse _any_ file that is in the `scripts` folder, where it didn't use to before.

[Our `scripts` folder is a git repository](http://i.imgur.com/SKaFE1W.png), so that it can be [pushed to and updated by GitHub](https://github.com/Gamealition/Survival-Skripts):

* [On our 1.10.2 live stable server running dev20, the `scripts` directory loads fine with git data ignored](http://i.imgur.com/R4c1wXy.png)
* [On our 1.11 BETA server running dev22, Skript attempts to parse everything, even binary files](http://i.imgur.com/pXDFp0E.png)

Obvious fix is to remove non-Skript files from `scripts`. I'm only commenting to confirm this is a regression.

**Comment by bensku** [comment]
Hmm, I guess I'll need to test this again.
