### ISSUE TITLE
Error in console! "is not a valid item data"

### ISSUE THREAD

**Issue by GabrielAugustoTI** [bensku/Skript#259]
Full server log: http://pastebin.com/vupggbbS

SkMorkaz
SkQuery-Lime 1.11 (unnoficial)
skRayFall_v1.9.5
Skript.jar latest release

Skripts:
http://pastebin.com/pcJtrLzB (carteira.sk)
http://pastebin.com/sf3GK8Wb (json.sk)
http://pastebin.com/dZtcmQ8q (SatoshiSkript.sk)

**Comment by Wasabules** [comment]
same error

**Comment by bensku** [comment]
Didn't I say that new Skript versions should not be used without addons. Anyway, there might be something useful in console log... SkQuery seems to report an error.

**Comment by melinstagibson** [comment]
I tried this the other day by **disabling all skript addons** and only using your latest version and it still happens.

all the code works i made so far tho, its just hard to find the real errors when everything is flooded with those fake errors.

also i watched every issue reported about this and the common addons are skrayfall and skquery.

to be honest i have no idea on how to help you reproduce this since its working on your system and i know you need to be able to do that to fix it.  if you want i can send you the whole plugin/server setup i have?

or is it maybe that you are using spigot and the people reporting it (including me) use paper?

**Comment by bensku** [comment]
PaperSpigot is possible cause, but not very likely. However, I'll keep that in mind.

**Comment by Wasabules** [comment]
I have spigot

**Comment by GabrielAugustoTI** [comment]
Latest version log: http://pastebin.com/ZRzN4kSp

**Comment by bensku** [comment]
SkQuery still incompatible. Need to check it.

**Comment by bensku** [comment]
I guess SkQuery works with latest build.

**Comment by GabrielAugustoTI** [comment]
;D
