### ISSUE TITLE
Date function returning weird values

### ISSUE THREAD

**Issue by Pyon-Pyon** [bensku/Skript#262]
Hey Bensku, as the title says, I tried to use the `date` function but it isn't returning the correct values. Just see:
![screenshot_37](https://cloud.githubusercontent.com/assets/23110519/20648931/5a0e4b0e-b492-11e6-8ba8-8f8f1f0df1bb.png)

Using the dev20b  with MundoSK, skDragon, SkUtilities, TuSKe, Gatt's SkQuery fix, RandomSK (with the SpecialSource fix), EventSK, SharpSK, SkRayFall, SkMoraz and SkStuff running Spigot 1.9.2-R0.1

**Comment by bensku** [comment]
Definitely a bug. Will take a look soon.

**Comment by TheBentoBox** [comment]
Looking at the DefaultFunctions.java real quick and I can't see exactly what's causing this to happen, but it's specifically because it always returns the time some number of hours before the time you request. In @Pyon-Pyon 's examples here, it's returning the time 3 hours before what is asked. I assume the time defaults to midnight, and in that, so asking for `date(2014, 10, 1)` gives the time 3 hours before midnight on October 1st 2014 (which is September 30th at 21:00, hence the 30/09/14 21:00 that's returned).

This differs between servers. On my server it always returns [5 hours before what I ask for](https://gyazo.com/63048318d771cb387d4abe389a3d6401) instead. I assume this is an issue with the time zone argument of the date function defaulting to the wrong value.

**Comment by bensku** [comment]
The date function takes arguments in UTC unless otherwise specified. What is kinda weird, since it prints it as local time, *and* incorrectly applies DST.

**Comment by bensku** [comment]
Well... Apparently it *didn't* take UTC after all, but instead Skript thought it was UTC all way. This has now been fixed. There is still something wrong with this function, but at least it seems to work.
