### ISSUE TITLE
PlayerInteractEvent debug spam

### ISSUE THREAD

**Issue by RoyCurtis** [bensku/Skript#265]
[It appears a debug output has been left in release `dev22c`, causing `PlayerInteractEvent` to write `PlayerInteractEvent` to the log.](https://vanderprot.gamealition.com/img/dea64.mp4)

* Version: [dev22c](https://github.com/bensku/Skript/releases/tag/dev22c)
* Tested on: `Paper version git-Paper-950 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)`

**Comment by TheLimeGlass** [comment]
Can confirm, I have this aswell.

Also 2 people have reported this same issue to me.

**Comment by Hcurt** [comment]
same

**Comment by Weefle** [comment]
Yep

**Comment by bensku** [comment]
Easy to fix, however next release will happen after I have done some other fixes too.

**Comment by Hcurt** [comment]
Not to rush anything or be rude, but in how long will it update?

**Comment by Immaridel** [comment]
I can confirm this as well.  Here is [3 seconds of logs](http://hastebin.com/eharibejiq.css), in which I right-clicked several times.

**Comment by TheBentoBox** [comment]
I feel like I'm the only one getting this @bensku since nobody else has said it yet, but I can't seem to use `clicked entity` in entity right click events anymore. I just tried with this being the only script on my server:

```
on right click on living entity:
	send "%clicked entity%" to the player
```

With [these plugins](https://gyazo.com/0ae80f7a3710eb0e9857eb3699613f7b) (AKA, no addons), and when I reload it I get [this](http://www.hastebin.com/ozonejisib.md). I'll try updating my Spigot and stuff now but otherwise I'm not really sure why it'd be doing this.

**Comment by WolfezzKyne** [comment]
Same

**Comment by bensku** [comment]
Fixed.

**Comment by RoyCurtis** [comment]
Thanks!
