### ISSUE TITLE
loop all players - causing freeze / lag

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#334]
When looping through all players (on a server with 100 players online) there is a noticeable freeze of ~ 1 - 2 seconds. Is this something that you could improve? 
We have other plugins running that loop through all players too without any noticeable lag.

**Comment by bensku** [comment]
Looping through all online players without any delays makes it to run during 1 tick. If server can't keep up, that tick will be longer, and so there will be lag spike. I recommend using delay of 1 tick inside loop.

Plugins might be able to just loop through that big list, since Skript's performance is very bad when compared to Java code. Or, those plugins might use delays like I recommended you to do. Actually, they might even do the looping asynchronously.

Skript's performance is not going to be improved with this codebase. Parsing speed, maybe, but not runtime performance.
