### ISSUE TITLE
Open inventory of block issue

### ISSUE THREAD

**Issue by Xpgrin** [bensku/Skript#338]
Hello

I'm using Skript Bensku fork + spigot 1.10 and I have problem with

open inventory of block

when I open inventory of block from unload chunk it opened and then close in a minute (or 30 second not sure) I think that chunk is unloaded and how to make inventory stay unless player close the inventory?

Bensku should enchant for this?

Thank

**Comment by TheBentoBox** [comment]
This is not something that Skript should make a workaround for. It is up to you to place blocks you want to open in chunks that are loaded or will always be loaded. Put blocks that you want to use this effect on in your spawn chunks, otherwise it would need a very hacky workaround involving canceling chunk unload events for chunks containing inventories that are currently opened to a player.

**Comment by Xpgrin** [comment]
This should be a enchantment :( nvm

**Comment by TheLimeGlass** [comment]
@Xpgrin Just load the chunk
