### ISSUE TITLE
Feature: More options for entities

### ISSUE THREAD

**Issue by minemidnight** [bensku/Skript#34]
Having more options for entities such as the age, donkey, mule, horse and specific types of things (such as the horses) can be helpful. Rabbit support would be cool too for their skins. Being able to use spawn a **baby zombie** for example.

**Comment by bensku** [comment]
Spawning baby zombie should work, Mirreski added support for it long ago. It might be bugged, though.

Different horse types are supported, and I could look at rabbit types. There is one limitation, however; if you spawn a non-default horse/rabbit with Bukkit API, you'll need to spawn normal horse first and change its type. Thus, spawn event gets wrong variant type.

Tl;dr I can do something, but without NMS code there are annoying limitations

**Comment by minemidnight** [comment]
So I can use mule and horse and donkey and stuff as different types?

**Comment by bensku** [comment]
You should be able to check if entity is mule, and spawn mules.

**Comment by TheBentoBox** [comment]
This is now all resolved, even more so as a side effect of the 1.11 update since the horse variants are now all different types. Just tested spawning baby and adult mules/donkeys/horses, all works on 2.2-dev22g.

Note that spawning baby llamas does **not** work right now, but Bensku is aware of this.
