### ISSUE TITLE
'on place of head' does not fire

### ISSUE THREAD

**Issue by StatelyMC** [bensku/Skript#342]
on the latest release, dev23, the 'on place of' event doesn't trigger for 'head' or 397 (the id of a head). Other place events seem to fire properly ('on place of tnt', for example), and the event-block of an 'on place' event can be properly accessed.

**Comment by FUZIK** [comment]
Please take a look at "aliases-english.sk" from main dirictory.

**Comment by StatelyMC** [comment]
I deleted the Skript directory and let skript generate a new aliases-english.sk - the issue persists. However, I was able to use an older (1.9) aliases file to resolve the problem. Might be a problem in the default aliases-english.sk

**Comment by TheBentoBox** [comment]
While the ID of the head item in-inventory is 397, the ID of the placed block is 144, so `on place of 397` will absolutely never fire (without changes on Mojang's end) because it's not a placeable block ID. It's as ineffective as asking for an event for placing a stick.

Are you sure you even checked the aliases file to see what the name of the block is? It doesn't seem like you did. The easiest thing to do is just run `send "%target block%"` while looking at a block to figure out what Skript calls it based on the aliases, because that's the name you'll need to put in the block place event.

For me, running that returned "mob head block" for a head mounted on a wall, and "floor head" for one on the floor. Tested with this code:

```
on place of floor head or mob head block:
	broadcast "Player placed %event-block% at %event-location%"
```

And [it worked perfectly](https://gyazo.com/32bc1adaf7feefc5a70fff31a656a183). So while I get the confusion, this is an issue with you using the wrong alias or ID, not an issue with the aliases themselves.
