### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by sandor111** [bensku/Skript#349]
My server stopped responding i see some erros from the skript plugin so i think i should post this here.
This is the crash log from the console: http://pastebin.com/LKbgjRcm
THis is the crash log: http://pastebin.com/Px4JDQSv
Minecraft server version: 1.8
Skript version: dev23 ( https://github.com/bensku/Skript/releases/tag/dev23 )

**Comment by Pyon-Pyon** [comment]
you should use at least the 1.8.8 (which isn't officially supported but it does work anyways) or this version of Skript wouldn't work in your server.

**Comment by sandor111** [comment]
@Pyon-Pyon on 1.8.8 the on explode event doesn't work. On 1.8.0 it does

**Comment by TheBentoBox** [comment]
1.8 isn't supported by this fork, and your actual crash log says the crash was due to an error while ticking entities, not Skript itself (if a plugin shows up in crash logs, that doesn't necessarily mean it caused the crash, just that it had procedures running when the crash happened that were dumped in the log).

**Comment by sandor111** [comment]
Okey i will report it to spigot
