### ISSUE TITLE
Suggestion: velocity expression

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#352]
This is a simple one to implement, as it can easily be fetched from the entity's nbt - more specifically the tag "Motion", which consists of three doubles, one for each axis. The velocity of the entity is simply whatever of these doubles is the highest number.

```
velocity of victim > 1
attacker's z-velocity != 0.5
loop-entity's horizontal velocity >= 0.01
```

Further, this allows for the addition of a simple alias expression:

`entity is moving`

which would be true if any number of the motion tag were greater than 0.0d

Cheers!

**Comment by Pyon-Pyon** [comment]
RandomSK has a velocity expression and if you want edit the NBT you can use skStuff. And it's not easy as you think, any nbt stuff need NMS (net.minecraft.server) and NMS makes the things version dependent and although you can use the Reflection, it's not recommended due to the lag it could cause and do an interface for support multiple version is a mess.
