### ISSUE TITLE
enchantment "sweeping edge" can't be applied

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#366]
```
command /asd:
    trigger:
        
        set {_item} to diamond sword
        enchant {_item} with sweeping edge
        add {_item} to command sender's inventory
```

thinking this just wasn't added to the latest skript version yet, i guess ^^

**Comment by TrademarkTM** [comment]
Something similar occours with the new "llama spit" and "shulker bullet" projectile from 1.11.
Error: https://hastebin.com/ovacasohun.md

My suggestion is also to add "list of all values for <type>", because it can be useful for things like `enchant player's tool with (list of all values for enchantmenttype)`.

**Comment by kairi2525** [comment]
`command /asd:
    trigger:
        
        set {_item} to diamond sword
        enchant {_item} with enchantments.names.sweeping_edge
        add {_item} to command sender's inventory`
