### ISSUE TITLE
Skript can't see colour codes <like &4> in arguments.

### ISSUE THREAD

**Issue by MiamiCenterPL** [bensku/Skript#388]
```
command /zmiennick [<text>]:
	trigger:
		if argument 1 is set:
			if argument 1 contains "&4":
				if player has permission "skript.red":
					execute player command "essentials:nick %argument 1%"
				else:
					message "&4Format zarezerwowany dla administracjii"
			else:
				execute player command "essentials:nick %argument 1%"
		else:
			message "&aWpisz swoj nick w kolorach!"`
```

Skript can't see &4 in argument 1, when I use command "/zmiennick &4Love" skript won't message me: "Format zarezerwowany dla administracjii", it will just change it, like if there's not &4 included... but if I change it to normal 4, everything works ;/ <I can't change it to 4, becouse some players have "4" in their nicks>

**Comment by TheBentoBox** [comment]
This isn't because Skript "doesn't see" it, it's because it automatically formats color codes whereas it may not consider the argument to be colored automatically. That being the case, this isn't a bug, you just need to experiment with the `[un]colored %text%` expression. e.g You may need to change it to `if colored argument 1 contains "&4"`.
