### ISSUE TITLE
"Does not contain" does not work when a list is empty.

### ISSUE THREAD

**Issue by SwiKZiiK** [bensku/Skript#404]
Hello.

I have a bug with the condition "does not contain".

When I use it on a list that is empty, the condition does not work while if I use it on a list that contains items, it works perfectly.

Example : 

```
command /test:
    trigger:
        if {my.list::*} does not contain "Test": # {my.list::*} is empty.
            send "Does not contain !"
        else:
            send "Contains !"
        # This will send me "Contains" while the list is empty.

# But if I use that :

command /test:
    trigger:
        add "..." to {my.list::*}
        if {my.list::*} does not contain "Test":
            send "Does not contain !"
        else:
            send "Contains !"
        # This will send me "Does not contain" because the list is not empty and does not contain the word "Test".
```

-> Skript version : DEV-24B.

**Comment by Tuke-Nuke** [comment]
Well, that's not really a bug but what happens is: When a variable doesn't have any values, it is considered a null object, so Skript returns false as the variable that variable didn't exists.
It can be changed btw, since in Skript it would make sense since the variable really doesn't have the value.

**Comment by bensku** [comment]
No values means no list, so it cannot contain anything.
