### ISSUE TITLE
List contains checks work improperly

### ISSUE THREAD

**Issue by AsDsDD** [bensku/Skript#411]
So at least list variable loops are broken. As an example, if {testvariable::\*} contains multiple values and "if {testvariable::\*} contains "asd":" is used, it doesn't find the value, even it contains it (if the variable contains just one value, it usually finds it) Same thing with "loop {testvariable::\*}" and "broadcast loop-value" won't broadcast right values. Using the newest build.

**Comment by Syst3ms** [comment]
First, it is known that lists of strings behave strangely/are broken. Also, can you detail your issue with code, screenshots and info like your minecraft version (as well as the exact Skript version). Also, to make stars appear, just use a `\\`. Like this : `\\\*`.

**Comment by AsDsDD** [comment]
So code like this won't work:
({test::*} contains "asd1" and "asd2")

command /test:
	trigger:
		if {test::*} contains "asd2":
			broadcast "Works!"
		else:
			broadcast "Doesn't work!"

It will print "Doesn't work!".

**Comment by TheBentoBox** [comment]
Yes, I've always had this issue and it's pretty frustrating. My info:

## Setup:
**Spigot:** git-Spigot-d4f98a3-4448a7e (MC: 1.11.2)
**Skript:** 2.2-dev25 (today's release, March 4th 2017)

## Test Code:
I used the following:
```
on script load:
	set {test::*} to "a", "b" and "c"
	loop {test::*}:
		broadcast loop-value
		if {test::*} contains loop-value:
			broadcast "List has %loop-value%"
		else:
			broadcast "List doesn't have %loop-value%"
```

## Result
Here's what's printed to my console when I run this:
![image](https://cloud.githubusercontent.com/assets/6902229/23581684/9fdaa48e-00e6-11e7-848c-ed2a7a67ff2c.png)

This is _very_ clearly incorrect, and it has been an issue for a long time. You're able to "solve" this issue by explicitly parsing the list and value as a string (i.e. `if "%{test::*}%" contains "%loop-value%"` does work very consistently), but there is then the obvious issue (in addition to needing to perform an unnecessary parse) that this can very easily lead to false positives. For example:

```
on script load:
	set {_letters::*} to "a", "b" and "c"
	set {_words::*} to "alamo", "bob" and "christina"
	loop {_letters::*}:
		broadcast loop-value
		if "%{_words::*}%" contains "%loop-value%":
			broadcast "Words list contains %loop-value%"
		else:
			broadcast "Words list doesn't contain %loop-value%"
```
This results in it broadcasting that the `{_words::*}` list contains each looped value of `{_letters::*}` when it clearly contains none of them (since parsing it as a string does a string contains check instead of list contains check). This is much less of an issue when checking contains for lists storing more complicated strings than single letters (such as UUIDs, which will never suffer from that false positive), but it can definitely be an issue in other situations if someone's not aware of that possible side effect and doesn't consider it when storing their values.

In general it's such a blatant and cumbersome issue when dealing with lists that it should probably be resolved soon, it's just been around so long that I think a lot of people have adapted.

**Comment by TheBentoBox** [comment]
Also, I should note this problem from your post...

> Same thing with "loop {testvariable::*}" and "broadcast loop-value" won't broadcast right values. 

... is not something I'm experiencing, as made evident by my test. It broadcasts the values correctly (though that was a simple test), but it doesn't do the contains check properly.

**Comment by SwiKZiiK** [comment]
I had the same problem before (https://github.com/bensku/Skript/issues/404), but the issue was closed, I do not know why.

**Comment by Moderocky** [comment]
I have always found that...
`if "whatever" is {things::*}:`
Works as a check for "whatever" being a member of "things".

**Comment by PheonBest** [comment]
It doesn't work for me @Moderocky.
@SwiKZiiK I get "It's not a valid item data". What version do you use ?

**Comment by bensku** [comment]
Could someone check if this still happens? I spent quite a lot time with parser to fix similar bug a month or so ago.

**Comment by DiscoverCard** [comment]
It's still happening.

**Comment by TheLimeGlass** [comment]
Is this the main "contains" issue? If so it should be renamed to the contains issue. All Skripters who have been within the community know that if two String values have similar names in a list, the contains won't work, that's the main issue. The second is since loop-value is coming from a variable. It is considered an object. An issue regarding this would be having proper type casts from variables. Like if you have a list of all strings and you loop that list variable. You can't use loop-string even though the list is mainly strings.

**Comment by TheBentoBox** [comment]
Good point about the rename @TheLimeGlass , I do believe this is the main contains issue.
