### ISSUE TITLE
Open inventory event bug

### ISSUE THREAD

**Issue by Weefle** [bensku/Skript#418]
The "inventory open" event don't work for the player!
`on inventory open:
	broadcast "&6Open"
on inventory close:
	broadcast "&4Close"` 
Video here: https://vimeo.com/207004102

**Comment by TheLimeGlass** [comment]
```
on inventory open:
	broadcast "Umm wat open %player%"
on inventory close:
	broadcast "Umm wat close %player%"
```
It looks like it's working fine in the video. Works fine for me aswell. What do you want the event todo?

**Comment by Weefle** [comment]
No, you don't understood the problem, this event works fine when I open all the inventories but not for the inventories of players. :/

**Comment by TheLimeGlass** [comment]
That's because it's client side 🍅

**Comment by Weefle** [comment]
Hmm, I did not know this, but if it's not a problem for bensku, this fix would be interesting! :D

**Comment by Ayase-san** [comment]
There is no fix such as there isn't a bug here, the InventoryEvent class doesn't have any support for the player's  inventory, if you want to detect that the only

**Comment by TheLimeGlass** [comment]
I went digging through the net.minecraft.server source code and I found out that the `PacketPlayInClientCommand` returns `PacketPlayInClientCommand.EnumClientCommand` and the enum `OPEN_INVENTORY_ACHIEVEMENT` is given everytime the player opens their inventory to check that the player has the achievement. This is basically a way to test if they open their inventory. This would need some NMS reflections in Skript for this to work, it would be a first for the project (NMS that is) so you can do this in Skellett. Here is your event
```
on packet:
	if event-string is "PacketPlayInClientCommand":
		if "%packet field ""a""%" is "OPEN_INVENTORY_ACHIEVEMENT":
			#do stuff
```
You can't cancel the event obviously though, because it's client side.

**Comment by Ayase-san** [comment]
Here the MundoSK way if you want too:
```
on packet event play_client_client_command:
    if "ClientCommand" penum 0 of event-packet = "OPEN_INVENTORY_ACHIEVEMENT":
        close player's inventory
```

**Comment by Weefle** [comment]
Ok thank you all, but I will use the "on packet" event of @TheLimeGlass because I like his addon! :D
