### ISSUE TITLE
'final damage' returns damage as individual health points while 'damage' and 'health' return it in hearts

### ISSUE THREAD

**Issue by ArchdukeLiamus** [bensku/Skript#425]
The final damage expression doesn't account for damage reductions, etc. and mirrors the damage expression's value.

To reproduce use this trigger
`on damage of player:
message "Victim: %health of victim% FinalDamage: %final damage%  Damage: %damage%" to attacker
`
and repeatedly hit an entity with armor. The victim's health will drop less than what the final damage expression reports for damage.

**Comment by TheBentoBox** [comment]
It's actually reporting a "correct" value, the actual problem is that `final damage` returns the amount of damage in _points_, while the `damage` and `health` expressions return the amount in _hearts_. So when a player takes two hearts of damage, but only ends up losing 1 heart, the final damage will be reported as 2 (because one heart = two health points), but their health will only have gone down by 1 (heart).

I've considered reporting this inconsistency for a while, since it's sort of strange for the various health and damage amount expressions to use different things. e.g. You can't check if a damage event would result in a player's death by doing `if final damage >= victim's health` (as you'd expect to be able to do), because that will fire any time they take half or more of their remaining health as final damage; you have to use `final damage/2`.

We'll see if Bensku wants to change this; it will be a breaking change for anyone using the final damage expression, but one for the better and that should probably happen eventually (so sooner is better).

**Comment by ArchdukeLiamus** [comment]
Thanks for the tip. I can't exactly confirm my suspicions that it's not accounting for armor, but the divide by 2 will do what I need it to do. I do think the change should happen because Skript should be using the same values for health.

**Comment by bensku** [comment]
Uh, this is a mistake. Final damage should be consistent with other damage expressions.

**Comment by ArchdukeLiamus** [comment]
Maybe it was a fluke or I had a bug in my code, I rewrote some damage handling code with `health of victim - (final damage) <= 0` and apparently it works just fine. So I guess it's not a bug after all?

**Comment by TheBentoBox** [comment]
That code will have false positives because, while it will trigger when the victim takes lethal damage, it will trigger additionally when the damage in points exceeds their health in hearts, as `final damage` returns damage in points. e.g. If someone has 3 hearts left, and they take 2 hearts of damage, the final damage will be 4, so that would equate to

```
3 - (4) <= 0
```

Which is of course true.

**Comment by ArchdukeLiamus** [comment]
Well, back to what I think was the original issue, I have to digress with your solution. The `final damage` expression does work correctly... when the victim is not wearing any armor or anything that reduces damage. When damage is supposed to be reduced, it's not accounting that in the value. So the right value being reported in regards to other values is not a bug. The fact that armor is not accounted for, is, given that I can deal scratch damage to a diamond armor player with an bow, and the moment they reach five hearts, it's an instant kill (because bows deal five hearts against targets with no armor). Your fix just happened to work for me only because iron armor happens to protect nearly one-half of damage, and even then I still had some undetected deaths that otherwise should have.

**Comment by bensku** [comment]
Yeah, I didn't have time to actually test this, but now I figured out that this is not bug of Skript.

Skript retrieves final damage from damage event directly; that is why I added it in first place. I have no interest to hack around Spigot's limitations.
