### ISSUE TITLE
Region expression not working in damage event

### ISSUE THREAD

**Issue by PugaBear** [bensku/Skript#435]
```
on damage of player:
	set {_l} to the location 1 meter above the victim
	set {_v} to "%victim%" parsed as a player
	send "%victim% %{_l}% %region at {_l}% %region at victim% %region at location of victim% %region at {_v}%" to console

	loop all players:
		if "%victim%" == "%loop-player%":
			set {_p} to loop-player
			send "%loop-player% %region at location of loop-player% %region at loop-player% %region at {_p}%" to console
```

![image](https://cloud.githubusercontent.com/assets/12417961/23981629/04ac9212-09d6-11e7-9ffe-0d687ea50ee4.png)

Ive tried everything I can think of, nothing is returning the region. I added waits, I tried it with functions. (http://paste.bn-mc.net/yihek.vbs = http://i.imgur.com/Cphc3j9.png)

It does work fine with 
```
command /myrg:
	trigger:
		send "%region at player%"

		loop all players: # this loop is the **exact** same loop as the one above, except %victim% is changed to %player%
			if "%player%" == "%loop-player%":
				set {_p} to loop-player
				send "%loop-player% %region at location of loop-player% %region at loop-player% %region at {_p}%"
```
![image](https://cloud.githubusercontent.com/assets/12417961/23981763/224fbf46-09d7-11e7-930d-249662ebce62.png)

I tried this on dev23 and dev25, and on a completely bare test server

![image](https://cloud.githubusercontent.com/assets/12417961/23986834/3848c26c-09f4-11e7-893d-d2828ed1f3ef.png)

**Comment by TheBentoBox** [comment]
Cannot reproduce on dev27 with no addons. I'm using your code at the top, created a region at my foot level called "lower" and a region at my head level called "upper" then teleported myself up enough to take fall damage once landing in the lower region. My result is as expected:

![image](https://cloud.githubusercontent.com/assets/6902229/25973787/941db2f4-3673-11e7-9004-9bcf0643c8c4.png)

I also want to note that your plugin list can't be correct, because in the provided code you used `==`, which is an SkQuery operator, meaning this script wouldn't even load properly with just the three plugins you mentioned, so you tested this with more plugins than you said.

If you confirm that you're still getting this issue in dev27 and show some way to reproduce, I'll reopen, but your exact code gives me no issue with or without addons (I tried both).
