### ISSUE TITLE
Format Slot!!!

### ISSUE THREAD

**Issue by UnknwonPerson** [bensku/Skript#436]
-format slot 0 of player with 101 named "Holaaaa" to be unstealable
 Will Spam
-format slot 0 of player with iron bars named "Holaaaa" to be unstealable
 Become Iron Ingot

**Comment by TheBentoBox** [comment]
1. `format slot` is an SkQuery syntax, so issues with it don't belong here.
2. This is just an issue with your aliases. Try changing it to `iron bar` instead of `iron bars`, or maybe just `bars`. In the end, you can check your aliases file to find out exactly what you should put.

Either way, this doesn't belong in a bug report, or certainly not one here.
