### ISSUE TITLE
min and max functions always return the first argument

### ISSUE THREAD

**Issue by Remixful** [bensku/Skript#460]
```
    set {_a} to max(1, 2, 3, 4)
    broadcast "&c%{_a}%"
```
returns 1
```
    set {_a} to max(6, 2, 3, 4)
    broadcast "&c%{_a}%"
```
returns 6

You can test these two pieces of code.

Edit:
Welp, I just found out that min is broken too.

```
    set {_a} to min(5, 2, 3, 4)
    broadcast "&c%{_a}%"
```

Returns 5

**Comment by Remixful** [comment]
I think the list is getting confused for arguments being passed into the function. 🤔

**Comment by TheBentoBox** [comment]
I've always had an issue with max never returning the right value, but never really looked into it since I don't use it much. You're definitely correct that it's just returning the first value; in fact, the `min` function does the exact same thing. Not sure if you're right about the reason, but @bensku will have to find out. Hopefully this is a quick fix because it would be nice for the next release (which seems to be approaching).

Good find.

**Comment by Snow-Pyon** [comment]
Not only in the max and min function, it happens on every function where I use a list made by parenthesis instead of a variable list. Example:
```
function test(test: objects) :: objects:
    return {_objects::*}

#And then call it like this:
test((1, 2, 3, 4 and 5))
```
Will just return 1, but if I do it like:
```
set {_input::*}  to 1, 2, 3, 4 and 5
Test({_input::*})
```
Will return the correct value.

**Comment by Tuke-Nuke** [comment]
The code of functions are really a mess to deal with it. Skript makes some weird work around to make it possible, for example, if you have an function with a list of argument, Skript make sure to convert this:
```
func("some", "list" and "here")
```
It tries to parse all values as a single argument, but not as 3 parameters values, since the function is declared as single paremeter, but list values
So it's really confusing, I think the best is the solution above, I don't know if Bensku would want to touch Functions now.

**Comment by bensku** [comment]
@Remixful @Tuke-Nuke Did dev29 fix this? Sorry, a bit late here...

**Comment by Snow-Pyon** [comment]
As my tests says, seems that it's fixed now.
