### ISSUE TITLE
Make color codes not override other formatting

### ISSUE THREAD

**Issue by bensku** [bensku/Skript#488]
... as it makes no sense. You can use <code>\<reset></code>

* [x] JSON chat - inherent support for stacking formatting options on top of each other, so done already
* [ ] Item names and other texts which require legacy code - will have to hack around a bit, but possible to do

**Comment by TheBentoBox** [comment]
The problem is that this is how it works in every other plugin (color codes overriding formatting). If you use Essentials's /i command to spawn in an item, setting its name using color codes will result in this behavior. If you set a region entry message in WorldGuard, [color codes use this behavior](https://gyazo.com/d501da360cf125b26574f3e50d400f27).

Personally, I get why this change would make much more sense, but I don't think it should be done given that years of scripts and plugins have set a precedence for the way it currently works, and it would break the formatting in a lot of old scripts. You're right that it doesn't really make sense, but in the same way that you can just use `<reset>`, you can also just redo the non-color formatting after changing color if you want it to continue. (And honestly, this strange behavior is often very useful, as I find more often than not that I don't want old formatting to continue when changing colors).

**Comment by bensku** [comment]
The thing is, it is harder than it sounds to make JSON chat color codes work as they'd work in old chat. But maybe I'll do it... Config option for it, probably.

**Comment by bensku** [comment]
Cancelled.
