### ISSUE TITLE
Formatting issue in dev26d

### ISSUE THREAD

**Issue by Classic36MC** [bensku/Skript#489]
Formatting still seems to be broken in dev26d.

In the my script file, `Prefix: &e&lEzMemes >&r` is set as the prefix option but in game, it shows like [this](http://i.imgur.com/lhLfmUV.png).

Spigot version: 1 version behind latest release

**Comment by bensku** [comment]
Wait a second... What exactly are you <code>send</code>ing?

**Comment by Classic36MC** [comment]
`send "{@Prefix} &7Commands:"` is an example. Rest of the script is here: https://www.spigotmc.org/resources/ezmemes.36654/

**Comment by TheBentoBox** [comment]
[Confirmed](https://gyazo.com/e1f349c9ce996f2bfd81b5055dd6b227), running this code:

```
options:
	Prefix: &e&lEzMemes >
on script load:
	send "{@Prefix} &7Commands: " to "Mr_Simba" parsed as player
```

Seems very strange, obviously something with having the single > is messing with the JSON parsing.

As per the other issues, though, I can confirm it's otherwise working much better @bensku! Just seems like edge cases like this with using angled brackets.

**Comment by Classic36MC** [comment]
Tried without the single > and returns [this](http://i.imgur.com/iicmKSI.png), though it can be resolved by putting &r at the end of the prefix.

`options:
	Prefix: &e&lEzMemes
on script load:
	send "{@Prefix} &7Commands: " to "Classic36" parsed as player`

**Comment by bensku** [comment]
Angle brackets breaking everything has been fixed now.
