### ISSUE TITLE
on region enter event doesn't contain region data

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#5]
**The issue:**
On Region Enter event doesn't give out any region data. %region at location of player% -> "<none>"

**Version:**
Latest Skript (by bensku).

**Spigot version:**
This server is running CraftBukkit version git-Spigot-3104eb1-daf4514 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Steps to reproduce:**
```
On Region Enter:
  broadcast " DEBUG: &a%player%&f On Region Enter (region at player: %region at location of player%)"

```

**Comment by bensku** [comment]
Actually, you should be able to get region data by using %event-region%, but that is bugging... I could fix it quickly, but I fear that might break other stuff.

**Comment by bensku** [comment]
Very hard to solve, after few hours of debugging yesterday I could not figure out why it doesn't work and gave up... Will try again once I have loots of time.

**Comment by Pilvinen** [comment]
on region enter and on region leave seem to be completely broken now. The only exception to this is teleporting in and out of the regions which works perfectly. %region% and %event-region% also works perfectly when teleporting in and out of regions.

When you walk, the events don't fire at all.

**Comment by TheBentoBox** [comment]
I've been having the same issue as Pilv. I actually reported it once [here](https://github.com/bensku/Skript/issues/21) but it randomly fixed itself while the server was still running. It started again a few days ago.

**Comment by TheBentoBox** [comment]
I may have found the issue? Keep in mind as I said before, I don't write plugins or know Java specifically, I'm just able to read it alright.

Towards the bottom of EvtRegionBorder.java, there's the code block which appears to actually be calling the region entry and leave events - casts the event to a PlayerMoveEvent, gets the previous and current location, and appropriately calls leave/entiry events respecitvely for regions at those location. In [this commit](https://github.com/bensku/Skript/commit/334555cbb0a87a91f4fd88c76904021f1fedb59c), you changed `if (to.equals(from))` to `if (to.equals(from) || to.distanceSquared(from) < 2)`, which was eventually changed to `if (to.getWorld().equals(from.getWorld()) && to.distanceSquared(from) < 2)` as a result of [this issue report](https://github.com/bensku/Skript/issues/12), which is what it is currently. 

I think the problem is that adding the `to.distanceSquared(from) < 2` makes the event really inconsistent when moving at low speeds, because it just straight up won't fire unless you've moved far enough in that move event. The distance moved shouldn't matter.

I'd recommend removing this chunk of code entirely, reverting it to the old behavior:
```if (to.getWorld().equals(from.getWorld()) && to.distanceSquared(from) < 2)
	return;```

**Comment by bensku** [comment]
I have no idea how, but this is fixed. Maybe some bug fix on Spigot?
