### ISSUE TITLE
damaging players from list bugs out

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#50]
Giving damage to players stored in list doesn't work:

```
command /test:
  trigger:
    loop players in radius 15 of location of player:
      set {_list::%UUID of loop-player%} to loop-player
    loop {_list::*}:
      damage loop-value by 0.5
```

**Comment by bensku** [comment]
This is certainly possible, but will be very slow - UUID lookup always is.

**Comment by TheBentoBox** [comment]
Can confirm this is still an issue, [here's what I ran in game to test](https://gyazo.com/d02430294673b8e1d758a4c97b7ce5f8). The first effect always does nothing, the last effect always throw [this stack trace](https://www.hastebin.com/ilacisifib.md). Note that this is the same error seen in Pyon's recent issue #299.

**Comment by Pyon-Pyon** [comment]
@TheBentoBox did you realize that you tried to do `damage random element out of of {test::*} by 10`. Also, I realized that it's a parsing error, I mean it doesn't parse it correctly. If you want it to work, you should do:
```
damage (random element of {test::*}) by 10
```
or:
```
set {_player} to random element of {test::*}
damage {_player} by 10
```
Didn't test if with the new parser it's the same due to the newer versions have the old parser.

**Comment by TheBentoBox** [comment]
You're right, I forgot the parentheses 👍 I just tested with the parens and it works with both syntaxes. Seems fine on dev22g -- I died both times.

Thank you for correcting my mistake @Pyon-Pyon, this seems to work fine.
