### ISSUE TITLE
'&k &l &m &o' not reset after other color code

### ISSUE THREAD

**Issue by marcellmit2l** [bensku/Skript#542]
Hello, I have found that the formatting code &k &l &m &o after a color code not be reset.

You should use &r to reset. > `&a&nHello &r&9this is blue`
It's not too bad, but I wanted to say it.

`send "&a&oTest1 &5&b&nTest2 &cTest3 &dTest4 &e&lTest5 &f&mTest6"`
<a href="http://www.directupload.net" target="_blank"><img src="http://fs5.directupload.net/images/170502/boljsbn3.png" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by Syst3ms** [comment]
I think this is intended behaviour

**Comment by TheBentoBox** [comment]
This really should not be the intended behavior, though. No other plugin in the history of ever has sent messages this way. If you set a region entry/exit in WorldGuard, color codes reset these markup codes. If you set up messages in Essentials (such as join messages, or using its books), color codes again will not work like this. 

I honestly can't say I understand the mentality behind this. Color codes should work *exactly* as Bukkit and Minecraft intends them to, which is with color codes resetting other codes. Even weirder is that specifying "colored" for messages in the new dev26 releases fixed many of the issues because it forces Skript to run the Bukkit colorizer on the message, making it work as intended, but we shouldn't really have to do that to get it to work like it should, especially since we never had to before and since this change causes unintended changes to literally every script ever written that sends any formatted messages. 

That's my two cents, at least.

**Comment by bensku** [comment]
If chat codes worked as Minecraft handles then with JSON chat, they would not work at all. Sure, I can do that too... but it is probably what you want.

Probably I'll just make toggleable hack for this, though I'm not sure how exactly that'd work.

**Comment by TheLimeGlass** [comment]
Closed? Also I like the older methods or i'm just used to it after all these years.

**Comment by nutella25** [comment]
The new enhancement makes i have to change all of my tons of skripts.
It will reset the color every variable set up, it's very annoying.
I hope you change it back to the older methods.

**Comment by bensku** [comment]
This has nothing to do with color codes reseting formatting (which they now, by default, do). What you're describing is a bug, which might be surprisingly hard to fix.
