### ISSUE TITLE
double %% does not work

### ISSUE THREAD

**Issue by losdevpath** [bensku/Skript#545]
I have script with this code:
`loop all players:
set {_OnlinePlayers} to placeholder "%%server_online%%" from loop-player`

Placeholder works but print `%1%` (one player). Image: http://i.imgur.com/HBdeETz.png

If use this `"%server_online%"` placeholder not work and print `<none>`.

Skript version: dev26f

**Comment by Snow-Pyon** [comment]
I don't know if it's a problem of Skript or Skellett on this case, I have the same issue but I haven't tried on the dev25 yet.

**Comment by TheLimeGlass** [comment]
I think it's a combination of Skript and PlaceholderAPI that is causing this issue.

Skript because you need to double quote a placeholder in order to get the actual placeholder. Or maybe it's placeholderAPI returning the %% with it.

My guess is it's a Skript issue. Try seing if another placeholder works or maybe try seeing if the double ruins other stuff.

In the end you can use `replace all "%" with "" in {_OnlinePlayers}`

**Comment by TheBentoBox** [comment]
I would move off of dev26 and go back to dev25 for now, it has a lot of issues parsing expressions and chat stuff in general.

**Comment by TheBentoBox** [comment]
@losdevpath do you still have this issue on the latest release (dev27)?

**Comment by bensku** [comment]
No response, closing.
