### ISSUE TITLE
Bug with function returns

### ISSUE THREAD

**Issue by Guarmanda** [bensku/Skript#557]
So it seems like there is a big bug with function returns. The problem, I think, is that returns aren never deleted but are still stored when we use a function multiple times. If a function returns something, as longer as the function can't return something, it will return the old return!
Example:
```
function(t: text) :: text:
    if {_t} is "hey!":
        return "lol" 
```
Here, if "{_t}" is hey just one time, the function will always return "lol" all the next times, either if the text isn't "hey!" It's, I think, an important issue...
The only workaround about that is be do add:
```
    if {_t} is not "hey!":
        return "ah, no!" 
```

**Comment by Pikachu920** [comment]
```
function func(t: text) :: text:
  if {_t} is "hey!":
    broadcast {_t}
    return "lol"`
```
and the output:
![](https://i.imgur.com/FqQJNGr.png)

**Comment by Syst3ms** [comment]
It's because Skript doesn't error when a return statement is missing, so it takes the only.one instead, undepending on the conditions that led to it

**Comment by TheBentoBox** [comment]
Yeah, this is weird but it's honestly a fault of your code. Not all of your possible paths return something. In most languages that wouldn't even compile for that very reason. 

I wouldn't even consider this a bug since it's on the user to write their functions correctly and return something if they say they're going to, though at the same time if it's at all feasible a nice enhancement would be to make functions that don't return something at all paths throw an error and not load. I don't see that being easy, though, and it's not really necessary, so it's up to bensku (personally I don't think it's worth the time unless it's way easier to do than I expect. since this isn't a problem for correctly written functions).

**Comment by TheBentoBox** [comment]
(Oops clicked close and comment instead of just comment #mobile)

**Comment by Syst3ms** [comment]
I think that it will be wayyy easier with the scope API that's coming, since you can just get all items in a trigger section

**Comment by TheBentoBox** [comment]
That definitely would make it easier.

**Comment by Syst3ms** [comment]
Well actually you could simply implement it already, since it's just about creating a field and setting it in a method, but there's lots of other stuff too, as you know

**Comment by Pikachu920** [comment]
@TheBentoBox @Snow-Pyon this can be closed now

**Comment by Syst3ms** [comment]
Let's not talk about what I had said here, shall we ?
