### ISSUE TITLE
Add support in 'on block form' event for silverfish infesting a block

### ISSUE THREAD

**Issue by PoweredDragon** [bensku/Skript#574]
Like in tittle. Make block form support silverfish eggs ✌️

**Comment by TheBentoBox** [comment]
I updated the title to better reflect what you were wanting to say because the way you worded it was confusing and could mean multiple things.

That being said, they shouldn't fire a `block form` event, because that event is for when a block is formed through natural world conditions. Really, this should be done by adding a new `on entity block change` event which uses [this Spigot event](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityChangeBlockEvent.html).

**Comment by TheBentoBox** [comment]
This will come in the next release as part of the `entity block change event`. The syntax will be `on silverfish enter` and `on silverfish exit`.
