### ISSUE TITLE
Skripts don't load

### ISSUE THREAD

**Issue by Jduffygames** [bensku/Skript#578]
I've had a lot of issues with Skript recently,

https://pastebin.com/D5gKg8h1

Whenever my server restarts, the Skripts do not load. So I had to have a spigot java plugin made to disable and then reenable the Skripts. None load unless I go through this process. I can't give the Skripts either because people will take them.

**Comment by Snow-Pyon** [comment]
It's an skQuery issue, not of Skript currently. To close.

And come on, no one is waiting on the shadows for you to post the scripts that you're using on your server, I'm pretty sure you don't have anything that unique to not put them here or anywhere. No offense but I think that's really stupid way of thinking knowing that there are plenty of awesome scripts people have done and published them for everyone, it's your decision anyways.

**Comment by TheBentoBox** [comment]
Agreed, don't flatter yourself, people aren't going to try to steal all of your ideas or scripts. Realizing that you're not a revolutionary is the first step towards making really cool stuff :)

This error is not occurring due to a vanilla Skript syntax, so this isn't the place to report it. Ask for help on the skUnity forums.
