### ISSUE TITLE
JSON chat and color formatting bug

### ISSUE THREAD

**Issue by Goetheus** [bensku/Skript#603]
Hi Bensku!

First of all, thank you for your work on Skript :)
I noticed a little bug with your new JSON chat system (thank you for this addon).

Minecraft version: 1.11.2
Spigot version: 1.11.2
Skript version: Dev27

I take an example:
```
send "<command:/mycommand>&bThis text is NOT clickable due to color formating!<reset>" to player
send "&b<command:/mycommand>This text IS clickable and coloured!<reset>" to player
```
It is the same with suggest command and tooltip.
So, when we use a color code inside the JSON section the JSON doesn't work.

Thank you to support this awesome plugin and to upgrade it!
Kiss <3

**Comment by TheBentoBox** [comment]
This is due to color codes resetting all formatting. There is a config option to disable this functionality (change `color codes reset formatting` from true to false), or just put the color outside of the tag.

I'm not sure if this should be fixed Skript-side as opposed to you personally doing either of those things, but a possible solution is making colors specifically not reset links while still resetting all style codes. Not sure if that's really feasible though, so it's up to @bensku.

**Comment by Goetheus** [comment]
> hange color codes reset formatting from true to false
Oh! Ok! Good, thank you for this information.

**Comment by bensku** [comment]
This is resolved in next build.
