### ISSUE TITLE
"on sign change" bug

### ISSUE THREAD

**Issue by HYPExMon5ter** [bensku/Skript#670]
So basically, there is an issue with the "on sign change" event, and it only seems to happen with 1 person.

Info:
Skript version: dev25
Minecraft version: 1.11.2 (but happened on 1.9.4 and 1.8.8 as well)
No errors

Code
```
on sign change:
	if line 1 is "[Buy]":
		if line 2 is set:
			if line 3 is set:
				if line 4 is set:
					loop 4 times:
						broadcast line loop-num of event-block
					set {_q} to "%uncolored line 2%" parsed as a integer
					set {_i} to "%uncolored line 3%" parsed as a item
					set {_p} to "%uncolored line 4%" parsed as a number
					replace all "$" with "" in {_p}
					set line 1 to "&3---&9[Buy]&3---"
					set line 2 to "&0&l%{_q}%"
					set line 3 to "&0&l%{_i}%"
					set line 4 to "&a&l$%{_p}%"
				else:
					set line 4 to "error"
			else:
				set line 3 to "error"
		else:
			set line 2 to "error"
```

![image](https://user-images.githubusercontent.com/12315186/27249197-a56235fe-52dd-11e7-8da3-bc7f75cd2bd6.png)

**Comment by Snow-Pyon** [comment]
What bug? Please be specific.

**Comment by HYPExMon5ter** [comment]
sorry, I accidentally pressed enter xD, fixed

**Comment by Snow-Pyon** [comment]
First of all, so horrible variable naming. And the issue is just that the parsing wasn't success not a bug.

**Comment by JarrenJ** [comment]
Bu the problem is that it only happens to me lol, no one else. Why would that happen? lol

**Comment by HYPExMon5ter** [comment]
it was a test lol, and it has to be a bug because we literally typed the SAME thing and there were no code changes and it works for my alt and everything, just him :(

**Comment by TheBentoBox** [comment]
Doesn't seem like a Skript-side issue to me. I've had players on my server who had issues with ChestShop and it turned out it was because they were on a Mac and it was adding extra invisible junk characters when editing signs, maybe something like that is the cause of your issue but otherwise it seems like a user error or something with conflicting events since it's working for literally everyone else, not something we can fix here.
