### ISSUE TITLE
Remove loop item from drops not reliable

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#696]
So i made a little soulbind skript that does:

```
on death of player:
    Loop drops:
        Lore of loop-item contains "soulbound"
        Remove loop-item from  drops
#etcblah```

Doesnt work reliably. In around 10% of the cases the item doesnt get removed and thus duplicates... i havent been able to figure out why it does that sometimes

**Comment by Snow-Pyon** [comment]
You would be better using `remove all` rather than just `remove`.

**Comment by melinstagibson** [comment]
Doesn't fix it

**Comment by melinstagibson** [comment]
i tried it by adding a variable {_lore} and set it to the itemlore and then check if the lore of the dropped item contains {_lore} which seems to fix it but thats just weird and i dont really trust this workaround unless someone can give me a logical reason why this works and what i posted doesnt :/

**Comment by TheBentoBox** [comment]
I actually have a Soulbound enchantment on my server and I can't confirm this behavior, however I _am_ putting the lore in a string, which may have something to do with it:

```
"%lore of loop-item%" contains "&7Soulbound"
```

Realistically this shouldn't be necessary since the lore should return a string anyways, but `contains` checks have always been bad (or at least unintuitive) in Skript. Can you check if putting the expression in text like that helps with your issue?
