### ISSUE TITLE
Cannot connect to server with skript on 1.12

### ISSUE THREAD

**Issue by manmadehuman** [bensku/Skript#698]
Using latest 1.12 Spigot
Skript ver. dev29

Get this error - https://pastebin.com/fBBdbvgS

When attempting to refresh server info from the MC server browser it repeats these errors in console.  cant connect.   COnnection works ok when skript is disabled. Removed all scripts and disabled all skript addons but left skript.jar enabled, issue still occurs. 

Only occurs with Protocollib.jar enabled.   Not sure if this is skript causing erros with protocol lib or vice versa.

Plugins List all at latest versions (with skript addons, issue still occurs with them disabled) - 
ParadiseLand, 
PlaceholderAPI, 
Craftconomy3, 
Thirst, 
RogueParkour, 
AutomaticInventory, 
AutoAFK, 
EpicWorldGenerator,
TreeFeller, 
Advanced-Fly, 
GekaMOTD, 
CoreProtect, 
WorldEdit, 
VoteRoulette, 
SimpleTrading, 
Skript, 
ArmorStandEditor, 
skDragon, 
SkQuery, 
WorldBorder,
 Votifier, 
Multiverse-Core, 
SeattleSummer, 
NoBonemeal, 
PermissionsEx, 
skUtilities,
 CS-CoreLib, 
mcMMO, 
Multiverse-Portals, 
Vault, 
MassiveCore, 
PerWorldInventory, 
CreativeGates, 
WorldGuard, 
ExtraHardMode, 
Slimefun,  
Essentials, 
SpigotLib, 
ProtocolLib,
LibsDisguises, 
NoCheatPlus,
Citizens, 
ExoticGarden, 
GriefPrevention, 
WorldEditSelectionVisualizer, 
SavageDeathChest, 
PickupArrows, 
skRayFall, 
MythicMobs, 
Wild, 
TitleManager, 
VentureChat, 
Orebfuscator4, 
mcMMOAction, 
Skellett, 
ProRecipes, 
TuSKe, 
BossShopPro, 
PlayerShops, 
ItemShops

**Comment by TheBentoBox** [comment]
There's nothing in that error message that indicates Skript is the cause of this, it's not even mentioned there. I additionally cannot reproduce this. Seems to me like you just need to update your ProtocolLib version or something, an outdated ProtocolLib can definitely cause players to be unable to connect.

If you can find a way to effectively reproduce this and show that it's definitely caused by Skript, please report back and I'll reopen.
