### ISSUE TITLE
Error loading a skript

### ISSUE THREAD

**Issue by ThePraZ** [bensku/Skript#703]
When I load/reload a specific skript, it make the server stops. It take too much time to load/reload.

Before I add like 20 lines to the skript, it took like 30 seconds to reload but after add the 20 lines, it makes the server stops. Please, help me.

The skript have 4616 lines (There are a lot of lines disabled)

PD: Also I want to know if is possible to get options from another skript, I mean, if I have a skript divided in 2 parts, how can I get in the part 2 the options from the part 1 without copying them.

I mean this:

Skript 1:
options:
	test: test

on join:
	send "{@test}" to player

Skript 2:
on quit:
	send "{@test}" to player

**Comment by TheBentoBox** [comment]
You already reported this in #702. Seriously, don't report the same issue twice when we already closed your first one because it's invalid. We **don't** support 1.8 or Skript 2.1.2. Please only report issues if you're using the latest release from the [releases page](https://github.com/bensku/Skript/releases) and are on 1.9 or above, otherwise we will **not** help you.

You can't reference options from other scripts. It's impossible. Make them variables or copy them over (I recommend the former if it's something you're going to need to reference in many scripts, there's no reason to not use a variable for that).
