### ISSUE TITLE
latest build ERROR

### ISSUE THREAD

**Issue by Someone-NEW** [bensku/Skript#710]
can be this fixed?
https://pastebin.com/uB5Km5Qi

**Comment by TheBentoBox** [comment]
What are you reporting, the fact that you put an invalid SQL option in your config, the `name conflict of variables` warning which can be disabled in the config and is due to your own code issues, or the `format slot` issues which are part of SkQuery (not Skript) and as such are invalid to report here?

Regardless of your answer, nothing in there validates a bug report here.

**Comment by Someone-NEW** [comment]
Tnx i solved
