### ISSUE TITLE
Click Event Not Working

### ISSUE THREAD

**Issue by A248** [bensku/Skript#734]
https://forums.skunity.com/threads/click-event-failing-in-some-cases.4460/

on leftclick holding mushroom stew:
    if player has permission "arim.soup":
        set {_prot} to spawnProt(player)
        if {_prot} is false:
            sendOwner("&5%name of player% &3–– &anormal soup leftclick.")
            soup(player)
    else:
        set player's action bar to "&cSoups disabled in this world"
 
on rightclick holding mushroom stew:
    if player has permission "arim.soup":
        set {_prot} to spawnProt(player)
        if {_prot} is false:
            sendOwner("&5%name of player% &3–– &anormal soup rightclick.")
            soup(player)
    else:
        set player's action bar to "&cSoups disabled in this world"

function soup(p: player): #Function is not called when leftclicking a block
    clear tool of {_p} #clear tool of {_p} does not work when rightclicking the air
    heal {_p} by 1 hearts
    remove regeneration from {_p}
    apply potion of regeneration of tier 3 to {_p} for 3 seconds
    play orb pickup at {_p} with pitch 1
 

Note: The sendOwner function is irrelevant. It works fine. It is simply helpful to debug stuff, which is why I have used it to try to debug this script. Also, the spawnProt function is irrelevant. It works in all of my other scripts.

No console errors, errors on load, etc.

Click holding mushroom soup:

- Leftclick in air: Works
- Leftclick on block: Event does not fire
- Rightclick in air: Item is not removed ('clear tool of {_p}' does not work)
- Rightclick on block: Works

**Comment by TheBentoBox** [comment]
We can't provide support for old versions of Skript, you're running dev23, and given that you're running on 1.8 you won't be able to update either. Sorry, but that's just how it is, we can't really provide support for 1.8 any longer. Best you can do is update to dev25 (as it seems to be the most stable version that still works on 1.8) and hope that it fixes some of your issues, but any remaining bugs in that version will have been fixed in newer releases that don't work on 1.8.
