### ISSUE TITLE
Alias inconsistencies involving skulls

### ISSUE THREAD

**Issue by Gamebuster19901** [bensku/Skript#739]
Just start right clicking with a skull and you will see that _mob_head_block and floor head are not considered a player head, this makes checking for heads cumbersome.

```
on place:
	cancel the event
	message "%event-block%"
	message "%player's held item%"
	if event-block is player head or _mob_head_block or floor head:
		cancel the event
```

**Comment by Gamebuster19901** [comment]
Also, this is in Skript v2.2-dev29

**Comment by Pikachu920** [comment]
This is because the skull type is stored in the `SkullType` nbt tag, its not an ID

**Comment by TheBentoBox** [comment]
This is likely just due to the player head inventory item having a different ID than the placed heads, which you're not accounting for. If you want one alias that can refer to both floor and wall heads, check the aliases file to make sure there isn't already one that you're not aware of, and if not, you can add it yourself and possibly make a PR to Tim's aliases repo with your addition.

Overall this appears to be either a user error (which invalidates the issue report) or an aliases issue (which means it should be reported to Tim).
