### ISSUE TITLE
Add 1.8.8+ Support to Dev29

### ISSUE THREAD

**Issue by rplcnn** [bensku/Skript#774]
I'm doing premium resources on SpigotMC. Too many players are waiting for 1.8.8+ support to Skript dev29+ @bensku please do that <3

**Comment by bensku** [comment]
Not particularly interested. Honestly, I greatly dislike premium *plugins* and scripts, well, even more.

Might fix 1.8 support anyway, but since I never really supported it, extremely low priority. If someone else would take care of 1.8 support, I would certainly be willing to co-operate. But spending my programming/support time for that... Unlikely to happen anytime soon.
