### ISSUE TITLE
getting blocks in chunk with list variable

### ISSUE THREAD

**Issue by xb0t3r** [bensku/Skript#790]
Minecraft server version 1.12 ( latest ) 
Bensku skript - devc30 (Latest)

So if you add a block in a chunk to a list then set that block in the chunk to a different block it'll update the list value? 

https://hastebin.com/orupinoqam.rb

Result:

Before - bedrock, bedrock, bedrock, bedrock
After - glowstone, glowstone, glowstone, glowstone

The list itself is not being updated with the new values?

Note: the original loop is not being run more than once and this is why the list itself is being updated cause the stop at the end stops it.

**Comment by TheBentoBox** [comment]
That's normal, you're storing a copy of the block in the list, a snapshot of its current value -- AKA, it passes by value, not by reference.

**Comment by xb0t3r** [comment]
and how do you copy it by reference?

**Comment by JeepSmash** [comment]
By storing the value - block at ***.  You are not storing information about the block type but a location of a block.   When stringified it will describe the block at that current location (in the map data file).   It can become difficult to make one line of code to record the block types at locations because of inventories and other special block properties that would be missed using - add type of block at **. So it depends on what type of blocks and their properties on how you would record them in a list

Another note-  using extrememely long variable names for logging info can drastically increase the size of your data file as every value stored in the data file is stored with its corresponding name which generally is larger (byte wise) than the actual value being stored (for most common data types like numbers and integers - but thats just my OCD talking

**Comment by bensku** [comment]
I think this is working as intended.
