### ISSUE TITLE
1.8 download

### ISSUE THREAD

**Issue by aycgit** [bensku/Skript#801]
```
events don't seem to work on dev30d 1.8.8 spigot

error: can't understand event

code
[hastebin](https://hastebin.com/gexebogebo.vbs) (the code should not be valid but the events should so that is why this issue exists, this code/script was just made waaay to fast)

for people saying it does not have 1.8 support, the issue page specifies untested but likely supported
if it is a problem with 1.8 things, could someone link me to a 1.8 version of skript?
```
oops it worked before but i guess 1.8 support broke somewhere between my last update long ago, could someone link me to a stable 1.8.8 download?

**Comment by HYPExMon5ter** [comment]
... you’re dumb, bensku’s fork doesn’t work on 1.8 past dev26 (I believe), I know dev25 works fine on 1.8 but it isn’t supported.

**Comment by bensku** [comment]
Yeah, 25/26 should work with 1.8, but they night have other issues. Plus of course they are missing a lot of new features.

**Comment by aycgit** [comment]
is there any work being done on 1.8 compat or has it been fully abandoned, this question is mainly because most servers out here are still 1.8-1.12

**Comment by TheBentoBox** [comment]
1.8 is not being worked on, and it's not even really "abandoned" because it was never even officially supported by this fork -- it just happened to still work on 1.8 for a while. Bensku has said that if someone wants to make a pull request to add 1.8 compatibility he'd be happy to merge it (barring other possible issues obviously), but I wouldn't expect him to work on it anytime soon. There are larger more important issues than catering to a specific subset of the community that is using a version that hasn't been up-to-date in over 1.5 years.

**Comment by aycgit** [comment]
okay, i thought that it would support 1.8 since like every server uses crossplay these days. (or i just haven't seen any 1.9 servers)

**Comment by TheBentoBox** [comment]
It's the latter (you just haven't seen them), there are tons of 1.9+ servers, my own included.

**Comment by bensku** [comment]
It is perhaps more about the fact that I never supported 1.8 so breaking it shouldn't be a big deal. I'm pretty sure only a few people run 1.9.x servers either, but one does not simply drop support for something that has always been there. 1.8, from my perspective has not been always there - it is surprising that it worked as long as it did.
