### ISSUE TITLE
"On Inventory Open" only fires on custom inventories or chests

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#851]
```
on inventory open:
    broadcast "event"
```
This will only trigger when a custom inventory or a chest is opened. As far as i can tell, anything but the player's inventory. In the docs.json it doesn't state that it's supposed to behave this way, so i thought (and hoped) this may be a bug/unintended behaviour.

If it is intended behaviour however, i would like to turn this topic into a suggestion. What i was trying to do was to force the player to open a GUI whenever he opens his inventory while sneaking. Trying to make players use as few text commands as possible here. :)

No error messages are generated.

Paper 1.12
Skript dev31

**Comment by Pikachu920** [comment]
This is the expected behavior, spigot's event doesn't cover it because there is no consistent way to detect when a player opens their own inventory (blame Mojang). It is possible to detect via statistics increase event and packets (both things not in vanilla skript) and some new way on 1.12. At the very least though a note should be added to the docs about this

**Comment by jaylawl** [comment]
I just checked on your information and unfortunately, there isn't even a statistic for how many times you've opened your inventory tracked by minecraft, which is propably also the reason there is no API event for this. Shucks ^^

**Comment by TheBentoBox** [comment]
Yeah, this can't really be fixed. You could probably use MundoSK's or Skellett's packet support for this, but it's not a bug on our end.

**Comment by Snow-Pyon** [comment]
Just to clarify, the way that it was done with packets before doesn't work anymore on 1.12+ due to the removal of the achievement system.
