### ISSUE TITLE
Use BlockFromToEvent in skript?

### ISSUE THREAD

**Issue by bertek41** [bensku/Skript#871]
Hey how can i use this event in skript is there any addon or? I need for give players reward when they mine cobblestone generator.

**Comment by TheBentoBox** [comment]
I believe the [spread event[(http://bensku.github.io/Skript/events.html#spread) fires for liquids but there is not currently vanilla Skript support for the `BlockFromToEvent`. Would be nice though, mainly for cancelling dragon egg teleportations.

**Comment by bertek41** [comment]
So is there any way i can check when player mine cobblestone generator?

**Comment by TheBentoBox** [comment]
There's no really good way to do that because there's no data stored on the cobblestone to indicate that it was formed from a cobble generator. You could try using the [block form event](http://bensku.github.io/Skript/events.html#form] to detect the formation of cobblestone, then store the formed block's location in a list and check for the location `on mine of cobblestone`, but the data isn't tied to the block so it wouldn't work well if the block was modified in any way other than mining (being blown up or moved by pistons).

**Comment by bertek41** [comment]
So the best way is java thanks :D

**Comment by bensku** [comment]
No data stored there applies to Java code also. Good luck.
