### ISSUE TITLE
on smelt event's "result slot of event-block" is broken

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#9]
**Skript version:**
Dev3

**Spigot version:**
This server is running CraftBukkit version git-Spigot-b1c1b55-7d73fbb (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**The issue:**
1) Place furnace
2) Smelt something
3) Try to detect what is in result slot.

**What happens:**
Only "block's result" works.

**What should happen:**
All the syntax should work, ie:

```
[the] (ore|fuel|result)[s] [slot[s]] of %blocks%
%blocks%'[s] (ore|fuel|result)[s] [slot[s]]
```

**Steps to reproduce:**
```
on smelt:
  if block's result is stone brick:        # This works
    broadcast " DEBUG: ""block's result"" works OK?"
  if result slot of event-block is stone brick:  # This doesn't work
    broadcast " DEBUG: ""result slot of event-block"" works OK?"
  if result slot of block is stone brick:   # This doesn't work
    broadcast " DEBUG: ""result slot of block"" works OK?"

```

**Comment by bensku** [comment]
Please report again if this is still broken, for me your test code works perfectly well now.

**Comment by Titeiiko** [comment]
Ik its a long time but this is for future people:
"on smelting:
	if ore slot of event-block is potato named "&aGrand Potato": 
		cancel event" 
Use a command like this.

When you use "on smelt" it has some exceptions (sometimes not working)
and use "ore slot" not "result slot" 
because if the result slot is air (before the smelt) and you're trying to target something then it won't work. 
It will work AFTER that item got smelted

(It's somewhat complicated but use the code above because I had a similar problem that helped my problem)
