### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by yyeerai** [bensku/Skript#90]
Customize new chest loot + entity Support (Nether fortress, temples, etc) (DeathTables)
Get version the world was created on.
Control spawning radius of a world's spawn
Gamerule expressions for disableElytraMovementCheck and spectatorsGenerateChunks
New sound support
New passenger support for entities, which allow to specifically set the order of the mobs. + 
Grab which version the player is on
Arrow potions
Set which direction the Shulker is attached to the wall.
Hopper minecart toggle syntax, to allow the minecart to pickup items or not.
Determine which phase the Ender dragon is in while fighting the battle.
Support for respawning the ender dragon the proper way.
Skeleton horse trap support.
**Better boat support, + passenger of boat, and row speed of boat.**
More support for Area clouds. (Umbaska only has a few syntax for support on this)
New command block support
Brewing stand fuel support
End gateway support
Scoreboard tag support is a thing now btw, so more coding options for scoreboards
Chorus and Chorus tree support
End ship, city and gateway support
Beetroot support with the crop grow
More shield support + colouring it like banner stuff in Umbaska
Potion status effect support
New statistics support (RandomSk is gone, so Umbaska?) xD

**Comment by bensku** [comment]
* Loot tables are not supported from Spigot API (actually even vanilla JSON format (https://hub.spigotmc.org/jira/browse/SPIGOT-1797)[is probably] broken
* Minecraft/Bukkit/Spigot version of world created is not directly available. I'm not going to dig it from world NBT data.
* Game rules could probably be supported, but you could also just execute console command
* New sound effects will be added when I rework effect system again.
* Passenger system should work with riding expression.
* Which version of... what player is on?
* Potions arrows will done when I have time.
* Shulker direction might not be supported by Spigot API.
* Events for hoppers need some enhancements, so you can get the minecart.
* Ender dragon is probably not supported by Spigot API.
* Respawning ender dragon is probably not supported by Spigot API.
* Skeleton horse traps were not supported when I tried to implement the support. Skeleton horses in general are supported (spawn skeleton horse).
* Boat support was bad in Spigot when I last checked. I'll see if it has changed. Speed of boat was deprecated at some point since "it was prone to breaking".
* Area effect clouds might be possible (as they're entities).
* Command block support is possible, and low priority.
* Brewing stand fuels should be easy to do.
* End gateway might not be supported by Spigot, and you could probably use on portal
* Scoreboard support is time consuming task, and you can use commands anyway. Low priority.
* Chorus plants should be pretty easy to do.
* Crop growth is terrible hack that I will replace at some point.
* Banners and shields should be possible to implement.
* Potion status effects are supported...  Do you mean custom potion items?
* Statistics might be possible at some point.

Nothing is going to happen very fast. I'm busy with other plugin, and I'd like to start porting Skript to Sponge soon (I mean, before 2017). Also I'd need to create some sort of documentation website...

**Comment by TheLimeGlass** [comment]
lol just realised I was the one to make this message. He just copied and pasted everything I said a long time ago xD

**Comment by Syst3ms** [comment]
Tipped arrows and potion support in general is in QuarSk, which will be eventually merged into Skript

**Comment by Syst3ms** [comment]
Same goes for banners and shields

**Comment by TheBentoBox** [comment]
Some of this has been added and a lot of it is invalid, making it a bit of a messy issue. Think this should be closed @bensku ? Or I could just clean up the initial list into a to-do checklist which reflects what's both possible & not implemented.

**Comment by bensku** [comment]
Hmm, I'll just close this. One request per issue is most clear.
