### ISSUE TITLE
Suggestion: loop %player%'s permissions

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#900]
Example:
```
loop event-player's permissions:
    "%loop-permission%" contains "important.node"
    console command "/permplugin %event-player% remove %loop-permission%"
```

Thanks for your time to read this.

edit:

a real practical application (my reason to post this in the first place):
```
function resetAchievements(player: player):
    loop {_player}'s permissions:
        "%loop-permission%" contains "game.achievement"
        console command "/permplugin %{_player}% remove %loop-permission%"
```

**Comment by Snow-Pyon** [comment]
the thing is that Skript doesn't hook into any permission plugins and having its own would be a kind of big task. We'll see what "bensku says about it.

**Comment by bensku** [comment]
Bukkit provides a way to check permissions. It would basically loop all players but call script only for the ones matching permission.

**Comment by Pikachu920** [comment]
Well, if such an expression was added people would also want to be able to add/remove from permissions

**Comment by JeepSmash** [comment]
you could possibly use a addon with file support and read the files the permission data is stored in to get those in a not so easy way... i know group manager stores them in an easy to read yml file which has lots of support from addons.  

Also it would probably be buggy because of encompassing perms with OPs and .* permissions since it would be able to return infinite amount of permissions

Another solution would be to track the achievements with a list variable - {achievements::%player%::*} rather than with giving and removing permissions just add and remove them from the list variable (assuming the permissions are not related to outside plugins)

yet another solution would be to store all of your achievement permission in a list variable {achievements::*} then use:
```
loop {achievements::*}:
  player has permission "game.achievement.%loop-value%"
  make console execute "/permplugin %player% remove game.achievement.%loop-value%"
```

**Comment by TheBentoBox** [comment]
This has been added (thanks @Blueyescat )
