### ISSUE TITLE
SKRIPTS ARE NOT LOADING!

### ISSUE THREAD

**Issue by Auswahluhr60042** [bensku/Skript#905]
Hello,

i have the version 2.2-30d... The problem is the skripts are not loading (/skript reload <my Skript>)

Error Code: https://pastebin.com/CeTdq0yN

Thank you.

**Comment by TheBentoBox** [comment]
1. You don't have dev30d, you have dev23, it says so right in the error report.
2. You're running 1.8, which is no longer compatible and as such, we can't help you with any errors. You won't even be able to benefit from any bugfixes we make because they'll be added to new versions which you can't use. At the moment it is essentially pointless for anyone running 1.8 to report bugs.
3. Duplicates #884.
