### ISSUE TITLE
Feature request: Add location for on weather change event

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#935]
I would like to do the following:
```
on weather change:
        log "Weather changed to %new weather% in %world%"
```
but
```
[10:05:00 INFO]: [Skript] Reloading log-weather.sk...
[10:05:00 ERROR]: There's no location in an on weather change event (log-weather.sk, line 8: log "Weather changed to %new weather% in %world%"')
[10:05:00 INFO]: [Skript] Encountered 1 error while reloading log-weather.sk!
```
Please consider adding this. With Multiverse-Core, each weather event occurs in a specific world.

**Comment by Blueyescat** [comment]
What are you talking about? I can't see any feature request here, of course there is no a location in weather change event. The point here is `%world%` doesn't work and gives that error, but `%event-world%` works. I tested it with Skript [2.2-170930-git-b1240c4](https://github.com/bensku/skript-build/blob/master/2.2-170930-git-b1240c4.jar) and [2.2-dev29](https://github.com/bensku/Skript/releases/tag/dev29), didn't work.
There is no any problem about `%new weather%`. 

Do you want to be added "location" to weather change event because the error message says "there is no location"? You change the title to **``"%world% gives an error in weather change event".``**

**Comment by SlimeDog** [comment]
I didn't consider it a bug, since there is no particular reason it should work. Therefore, a feature request. However, event-world is fine for my purposes, so I'm closing it.
