### ISSUE TITLE
All entities should be killable

### ISSUE THREAD

**Issue by Pikachu920** [bensku/Skript#937]
Skript should handle deletion or killing when the kill effect is used. It not doing this can lead to confusion (see #934)

**Comment by supertassu** [comment]
This is weird as it's already in the code: https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffKill.java#L74

**Comment by TheBentoBox** [comment]
It's sorta in the code @supertassu , but that code has specific checks for some entities as opposed to working on everything non-living. Honestly, I'm not sure how that `if` statement even works given that Pigs, Armor Stands, and Ender Dragons are Damageable, meaning the statement should never pass for them. The separate checks for the entity being an instance Vehicle or Pig are probably also redundant since Pigs are already Vehicles, but I'm not super familiar with how Bukkit/Java type comparisons work so perhaps it's necessary.

In my head that whole statement could be simpler and look like this:
```
if (entity instanceof Damageable) {
    entity.setHealth(0);
}
else {
    entity.remove();
}
```

I can only imagine it's being made more complicated than that for a reason.

**Comment by Pikachu920** [comment]
I imagine it uses damage instead of sethealth so that the damage sound plays

**Comment by bensku** [comment]
Old Spigot versions have had Damageable missing, if I remember correctly. Since we support 1.9+, we need to work around this.
