### ISSUE TITLE
code running when it shouldn't be

### ISSUE THREAD

**Issue by HYPExMon5ter** [bensku/Skript#939]
Skript version: dev31c
Minecraft version: 1.12.2

Original Code:
```
function nextName(tool: Item, list: Objects):
	if display name of {_tool} is set:
		set {_name} to name of {_tool}
		set {_i} to 1
		loop {_list::*}:
			if {_i} is equal to size of {_list::*}:
				set name of {_tool} to "%{_list::1}%"
			else:
				add 1 to {_i}
				if "%loop-value%" is {_name}:
					set name of {_tool} to "%{_list::%{_i}%}%"
	else:
		set name of {_tool} to "%{_list::1}%"

command /nextname:
	trigger:
		set {_names::*} to "1", "2" and "3"
		nextName(player's tool, {_names::*})
```

Fixed Code:
```
function nextName(tool: Item, list: Objects):
	if display name of {_tool} is set:
		set {_name} to name of {_tool}
		set {_i} to 1
		loop {_list::*}:
			if {_i} is equal to size of {_list::*}:
				set name of {_tool} to "%{_list::1}%"
                                stop
			else:
				add 1 to {_i}
				if "%loop-value%" is {_name}:
					set name of {_tool} to "%{_list::%{_i}%}%"
                                        stop
	else:
		set name of {_tool} to "%{_list::1}%"

command /nextname:
	trigger:
		set {_names::*} to "1", "2" and "3"
		nextName(player's tool, {_names::*})
```
So this code should work perfectly fine, it should start at 1 and increase each time you run the command until you hit 3 and when you run the command again it'll reset back to 1, but that's not the case at all, if you look at the fixed code and put broadcasts where the stops are instead, when you run the command it'll broadcast both messages.

**Comment by TheBentoBox** [comment]
Your report also isn't very clear; which `else` are you talking about adding broadcasts before and after? How do you add a broadcast right before an else? You shouldn't be able to put anything between the if block and the else line (aside from white space). Where did you add the `stop` to fix it?

**Comment by HYPExMon5ter** [comment]
I just edited it, should make it a bit more clear

**Comment by supertassu** [comment]
You're trying to compare name of the tool (a string) with size of the array (an integer).

**Comment by HYPExMon5ter** [comment]
They’re both strings and it doesn’t matter, it still shouldn’t be running both

**Comment by supertassu** [comment]
It's running both? Oh.

**Comment by HYPExMon5ter** [comment]
Yes it’s running the if and the else

**Comment by supertassu** [comment]
Wait a second.. It's running them both because your loop continues even if it matches it? Have you tried `stop loop` instead of `stop` (they can be buggy sometimes)?

**Comment by HYPExMon5ter** [comment]
Right but it should only run the if or else.. stop fixes it, but there shouldn’t have to be a stop

**Comment by JeepSmash** [comment]
To properly work your code should look like this:  (line numbers added for reference)

```
1 function nextName(tool: Item, list: Objects):
2 	if display name of {_tool} is set:
3 		set {_name} to name of {_tool}
4 		set {_i} to 1
5 		loop {_list::*}:
6 			if {_i} is equal to size of {_list::*}:
7 				set name of {_tool} to "%{_list::1}%"
8 			else:
9 				add 1 to {_i}
10				if "%loop-value%" is {_name}:
11					set name of {_tool} to "%{_list::%{_i}%}%"
12					stop
13	else:
14		set name of {_tool} to "%{_list::1}%"
15
16 command /nextname:
17 	trigger:
18		set {_names::*} to "1", "2" and "3"
19		nextName(player's tool, {_names::*})
```

There is no problem with skript but the way your code was flowing.  Once your code matched the name of the item with the name in the list (line 10) it still continued to loop the list (line 5) and increment {_i} (line 9) until it reached the last entry in the list at which point it will match {_i} with the size of the list (line 6)  So any time you ran your original code without a stop placed at line 12 and the item had a name contained in the list it would set the name of {_tool} 2 separate times under those 2 conditions.  Once a stop (or anything else to escape the loop on line 5) is placed on line 12 it will not allow for both conditions to be met in one instance of the function.    Yes it would run the if and the else when running the function but they would not both run during the same loop instance.

I also noticed that you may have overlooked the value of your index in the list when implementing your loop.  The first index of a list is 0 not 1 if building the list with "add {_value} to {_list::*}".  There would be some undesired operation from your code since {_i} would equal your list size prior to looping the last entry in your list as well as having {_i} offset from your real index by 2 instead of 1 when setting the item name to the next list value.

**Comment by HYPExMon5ter** [comment]
ah yeah, you're right, I'd need a stop after I set the name of the tool to the next string in the list. Didn't catch that.
