### ISSUE TITLE
The {something.%player%} Glitches When it's Met With a Damage Event

### ISSUE THREAD

**Issue by Techno3600** [bensku/Skript#959]
Hello,
The code thinks that when this happens:
```
on damage of an entity:
    if {eda} is true:
        if {bypass.%player%} is false
            cancel event
```

It thinks it must be:

```
on damage of an entity:
    if {eda} is true:
        if {bypass.%victim%} is false
            cancel event
```

Because when a damage event is called it must be victim, but I can't change the variable to victim because it needs to be player (self-explanatory, also the indentation is correct in the actual skript)

Thanks
Techno

**Comment by TheBentoBox** [comment]
Well, to start, I fixed your code display issues. Check how your post is formatted now to see how code formatting works with markdown.

As for the actual issue, `%player%` isn't really the correct expression to use in a damage event most of the time, especially since many damage events won't contain a player so you're checking for a player in an event that doesn't have one, which is why you're seeing it default to `victim` instead. Personally I think that you shouldn't even be allowed to use `player` in damage events but there may be a situation I'm not considering. But if you want it to only fire when a player is damaged, just change the event to be `on damage of player` instead of `on damage of an entity`:

```
on damage of player:
    {eda} is true
    {bypass.%victim%} is false
    cancel event
```
