### ISSUE TITLE
add event On pulling a bow <Time>:

### ISSUE THREAD

**Issue by Dylan123111** [bensku/Skript#963]
I was working on a skript for a bow that shoots arrows with particles, I wanted the bow to only be able to fire these arrows with particles when the player pulled the bow for 1.2 seconds, but that is inpossible with skript for as far as i know, it would be really appreaseaded by a lot of the users of skript if you would add this event, or a way to make this possible.

**Comment by Pikachu920** [comment]
It's possible with skript and this is definitely not something many people want. Spigot has no corresponding event anyway.

**Comment by Dylan123111** [comment]
Feel free to tell me how thats possible (pls)

**Comment by hazycraft** [comment]
you can use on right click: and use server ticks to track how long someone has right clicked... I'm not writing skript for you, you need to do that.

**Comment by TheLimeGlass** [comment]
This isn't possible. The client doesn't send any packets notifying the server of a player loading a bow. You have to use common sense and calculate the time it has taken such as what Hazy said. On rightclick wait few ticks, test if they shot. boom your time they took to load.

**Comment by Pikachu920** [comment]
Yes it does? A quick look at wiki.vg reaffirms this.
![image](https://user-images.githubusercontent.com/28607612/32942115-9de98afa-cb4d-11e7-963d-66b6a31854f1.png)

**Comment by TheBentoBox** [comment]
IMO this is something that a user should implement themselves if they need it since all of the tools are already in place and there's no good way via Spigot to do what the report is asking (`on pulling a bow %time%`).

Just to give you an idea @Dylan123111: 
```
on right click:
    event-item is a bow
    set {bowDrawTime::%player's UUID%} to now
on shoot:
    shooter is a player
    if difference between {bowDrawTime::%shooter's UUID%} and now >= 1.2 seconds:
        <PARTICLES>
    delete {bowDrawTime::%shooter's UUID%}
```
This should do roughly what you want. It's untested so it might need some changes, but if this works for you then this should be closed IMO. Bensku would basically need to do this same thing behind-the-scenes to add support for this.

**Comment by TheBentoBox** [comment]
Since there's a general agreement that this doesn't make sense to add and there hasn't been a response in five days, I'm closing this.
