### ISSUE TITLE
NaN can be parsed as a number

### ISSUE THREAD

**Issue by Pikachu920** [bensku/Skript#970]
```vb
command nan:
  trigger:
    broadcast "%""NaN"" parsed as a number%"
```

Results in NaN when it should be \<none>

**Comment by bensku** [comment]
NaN is, despite being shorthand for "not a number", a valid IEEE 754 floating point number. I see nothing wrong here.

**Comment by Pikachu920** [comment]
Perhaps instead of closing the issue you could have asked why it's an issue? It doesn't follow Skript logic. It breaks common uses such as
```
command /test <text>:
  if arg-1 parsed as a number is set:
    set {_number} to arg-1 parsed as a number
    add 1 to {_number}
    broadcast "%arg-1% + 1 = %{_number}%"
  else:
    send "please use a number"
```

**Comment by Pikachu920** [comment]
In addition to not following Skript logic, they don't even work correctly.
```

command /nan:
  trigger:
    if NaN is NaN:
      broadcast "NaN is NaN"
    else:
      broadcast "NaN is not NaN"
    if "Infinity" parsed as a number is "Infinity" parsed as a number:
      broadcast "Infinity is Infinity"
    else:
      broadcast "Infinity is not Infinity"
    if "-Infinity" parsed as a number is "-Infinity" parsed as a number:
      broadcast "-Infinity is -Infinity"
    else:
      broadcast "-Infinity is not -Infinity"   
```
produces

![](https://i.imgur.com/LBGbTtf.png)

**Comment by bensku** [comment]
Problems with positive and negative infinity were not outlined in original bug report. According to the standard, NaN does not equal with itself, according to the standard.

Using NaN or Infinity in most expressions is obviously a bad idea. It can be exploited, too. Still, it follows the standard and Java's implementation of floating point numbers... IMO it is scripters' responsibility to check that the input is valid.

It should be done even without possibility of special numbers. What if a player is teleported too far away from the world center ("far lands")? What if a speed of player is set to some ridiculous number? (it likely crashes the server and client, no need to use infinity)

That all being said, Infinity comparisions are indeed broken. It is a bug.

I might also consider disabling special numbers in command arguments and (optionally) even parse-syntax. Also, documentation could use an adjustment. Still, it is not about what I consider to be sensible numbers: who am I to choose that? It is generally better to follow standards than to "pick what makes sense" (since it often doesn't for other people). At least people can go to Wikipedia and read about floating point numbers without having to guess if Skript implements then differently...

**Comment by Pikachu920** [comment]
Should we remove null checks then? Juts because it's the scripters' responsibility? How do you even expect someone to check this in the first place? Lets say someone happens to know about the existence of NaN, Infinity and -Infinity within skript. They write the following check
```
command /speed <text>:
  trigger:
    if arg-1 parsed as a number is not NaN or Infinity or -Infinity:
      set player's walk speed to arg-1 parsed as a number
```
but oh wait, that doesn't work because comparisons are broken. So in order for a scripter to properly protect against this they would have to a. know NaN, Infinity and -Infinity exist, b. know they can be parsed as numbers and c. know that direct comparisons won't work. This is not a very realistic scenario.
